use_frameworks!
pod 'MicrosoftFluentUI', '~> 0.2.6'
target 'AdaptiveCards' do
  project './AdaptiveCards/AdaptiveCards.xcodeproj'
  target 'AdaptiveCardsTests' do
      inherit! :complete
  end
end

target 'ADCIOSVisualizer' do
  project './ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj'
  target 'ADCIOSVisualizerUITests' do
  end
end

workspace 'AdaptiveCards'
platform :ios, '13'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
    config.build_settings['ENABLE_BITCODE'] = 'YES'
  end
end
