use_frameworks!
pod 'MicrosoftFluentUI', '0.1.9'
target 'AdaptiveCards' do
  project './AdaptiveCards/AdaptiveCards.xcodeproj'
  target 'AdaptiveCardsTests' do
      inherit! :complete
  end
end

target 'ADCIOSVisualizer' do
  project './ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj'
  target 'ADCIOSVisualizerUITests' do
  end
end

workspace 'AdaptiveCards'
platform :ios, '13'

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
