id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - daily:
          time: 9:0
      filters:
      - isPullRequest
      - isOpen
      - noActivitySince:
          days: 5
      - isNotLabeledWith:
          label: no-recent-activity
      - isNotLabeledWith:
          label: Spec
      actions:
      - addLabel:
          label: no-recent-activity
      - addReply:
          reply: 'Hi @${issueAuthor}. This pull request has had no recent activity for the past **5 days** . Please take the necessary actions (review, address feedback or commit if reviewed already) to move this along. '
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      then:
      - addCodeFlowLink
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - isAction:
          action: Submitted
      - isReviewState:
          reviewState: Changes_requested
      then:
      - addLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: 'Needs: Author Feedback'
      then:
      - removeLabel:
          label: 'Needs: Author Feedback'
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: no-recent-activity
      - isAction:
          action: Edited
      then:
      - removeLabel:
          label: no-recent-activity
      - addReply:
          reply: Staleness reset by ${contextualAuthor}
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - isActivitySender:
          user: productboard-ac
          issueAuthor: False
      then:
      - addLabel:
          label: Feature
      description: 
    - if:
      - payloadType: Pull_Request
      - or:
        - includesModifiedFiles:
            files:
            - source/nodejs/adaptivecards
        - includesModifiedFiles:
            files:
            - source/nodejs/adaptivecards-site
        - includesModifiedFiles:
            files:
            - source/nodejs/adaptivecards-designer
        - includesModifiedFiles:
            files:
            - source/nodejs/adaptivecards-visualizer
      - or:
        - isAction:
            action: Opened
      then:
      - addReply:
          reply: Hi @${issueAuthor}. Thanks for helping make the AdaptiveCards JS renderer + tooling better. As additional verification, once the JS build succeeds, please go to the [test site](https://adaptivecardsci.z5.web.core.windows.net/pr/${number}) to test out your website/designer changes.
      description: 
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: no-recent-activity
      - or:
        - isAction:
            action: Synchronize
        - isAction:
            action: Null
        - isAction:
            action: Closed
        - isAction:
            action: Null
      then:
      - removeLabel:
          label: no-recent-activity
      - addReply:
          reply: Staleness reset by ${contextualAuthor}
      description: 
    - if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - not:
          isActivitySender:
            user: productboard-ac
            issueAuthor: False
      then: []
      description: 
    - if:
      - payloadType: Issues
      - labelAdded:
          label: MSTeams-Developer-Support
      then:
      - closeIssue
      description: 
onFailure: 
onSuccess: 
