//
//  ACFramework.h
//  ACFramework
//
//  Copyright © 2017 Microsoft. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for ACFramework.
FOUNDATION_EXPORT double AdaptiveCardsFrameworkVersionNumber;

//! Project version string for AFramework.
FOUNDATION_EXPORT const unsigned char AdaptiveCarsFrameworkVersionString[];

#import "ACOAdaptiveCard.h"
#import "ACOAdaptiveCardParseResult.h"
#import "ACOBaseCardElement.h"
#import "ACOEnums.h"
#import "ACOHostConfig.h"
#import "ACOHostConfigParseResult.h"
#import "ACOIResourceResolver.h"
#import "ACOInputResults.h"
#import "ACOMediaEvent.h"
#import "ACORemoteResourceInformation.h"
#import "ACORenderContext.h"
#import "ACOResourceResolvers.h"
#import "ACRAVPlayerViewHoldingUIView.h"
#import "ACRActionDelegate.h"
#import "ACRActionExecuteRenderer.h"
#import "ACRActionOpenURLRenderer.h"
#import "ACRActionOverflowRenderer.h"
#import "ACRActionSetRenderer.h"
#import "ACRActionShowCardRenderer.h"
#import "ACRActionSubmitRenderer.h"
#import "ACRActionToggleVisibilityRenderer.h"
#import "ACRAggregateTarget.h"
#import "ACRBaseActionElementRenderer.h"
#import "ACRBaseCardElementRenderer.h"
#import "ACRButton.h"
#import "ACRChoiceSetViewDataSource.h"
#import "ACRChoiceSetViewDataSourceCompactStyle.h"
#import "ACRColumnRenderer.h"
#import "ACRColumnSetRenderer.h"
#import "ACRContainerRenderer.h"
#import "ACRContentHoldingUIScrollView.h"
#import "ACRContentHoldingUIView.h"
#import "ACRCustomActionRenderer.h"
#import "ACRCustomRenderer.h"
#import "ACRDateTextField.h"
#import "ACRErrors.h"
#import "ACRFactSetRenderer.h"
#import "ACRIBaseActionElementRenderer.h"
#import "ACRIBaseCardElementRenderer.h"
#import "ACRIBaseInputHandler.h"
#import "ACRIMedia.h"
#import "ACRImageProperties.h"
#import "ACRImageRenderer.h"
#import "ACRImageSetRenderer.h"
#import "ACRImageSetUICollectionView.h"
#import "ACRInputChoiceSetRenderer.h"
#import "ACRInputDateRenderer.h"
#import "ACRInputLabelView.h"
#import "ACRInputNumberRenderer.h"
#import "ACRInputRenderer.h"
#import "ACRInputTableView.h"
#import "ACRInputTimeRenderer.h"
#import "ACRInputToggleRenderer.h"
#import "ACRLongPressGestureRecognizerFactory.h"
#import "ACRMediaRenderer.h"
#import "ACRMediaTarget.h"
#import "ACRNumericTextField.h"
#import "ACROverflowTarget.h"
#import "ACRParseWarning.h"
#import "ACRQuickReplyMultilineView.h"
#import "ACRQuickReplyView.h"
#import "ACRRegistration.h"
#import "ACRRenderResult.h"
#import "ACRRenderer.h"
#import "ACRRichTextBlockRenderer.h"
#import "ACRSeparator.h"
#import "ACRShowCardTarget.h"
#import "ACRTargetBuilderDirector.h"
#import "ACRTextBlockRenderer.h"
#import "ACRTextField.h"
#import "ACRTextInputHandler.h"
#import "ACRTextView.h"
#import "ACRToggleInputDataSource.h"
#import "ACRToggleInputView.h"
#import "ACRToggleVisibilityTarget.h"
#import "ACRUIImageView.h"
#import "ACRUILabel.h"
#import "ACRView.h"
