/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class ContainerOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContainerOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContainerOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ContainerOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSeparation(SeparationOptions value) {
    AdaptiveCardObjectModelJNI.ContainerOptions_separation_set(swigCPtr, this, SeparationOptions.getCPtr(value), value);
  }

  public SeparationOptions getSeparation() {
    long cPtr = AdaptiveCardObjectModelJNI.ContainerOptions_separation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SeparationOptions(cPtr, false);
  }

  public void setNormal(ContainerStyleConfig value) {
    AdaptiveCardObjectModelJNI.ContainerOptions_normal_set(swigCPtr, this, ContainerStyleConfig.getCPtr(value), value);
  }

  public ContainerStyleConfig getNormal() {
    long cPtr = AdaptiveCardObjectModelJNI.ContainerOptions_normal_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContainerStyleConfig(cPtr, false);
  }

  public void setEmphasis(ContainerStyleConfig value) {
    AdaptiveCardObjectModelJNI.ContainerOptions_emphasis_set(swigCPtr, this, ContainerStyleConfig.getCPtr(value), value);
  }

  public ContainerStyleConfig getEmphasis() {
    long cPtr = AdaptiveCardObjectModelJNI.ContainerOptions_emphasis_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ContainerStyleConfig(cPtr, false);
  }

  public ContainerOptions() {
    this(AdaptiveCardObjectModelJNI.new_ContainerOptions(), true);
  }

}
