/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class FontSizeOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FontSizeOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FontSizeOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_FontSizeOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSmallFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizeOptions_smallFontSize_set(swigCPtr, this, value);
  }

  public long getSmallFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizeOptions_smallFontSize_get(swigCPtr, this);
  }

  public void setNormalFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizeOptions_normalFontSize_set(swigCPtr, this, value);
  }

  public long getNormalFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizeOptions_normalFontSize_get(swigCPtr, this);
  }

  public void setMediumFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizeOptions_mediumFontSize_set(swigCPtr, this, value);
  }

  public long getMediumFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizeOptions_mediumFontSize_get(swigCPtr, this);
  }

  public void setLargeFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizeOptions_largeFontSize_set(swigCPtr, this, value);
  }

  public long getLargeFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizeOptions_largeFontSize_get(swigCPtr, this);
  }

  public void setExtraLargeFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizeOptions_extraLargeFontSize_set(swigCPtr, this, value);
  }

  public long getExtraLargeFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizeOptions_extraLargeFontSize_get(swigCPtr, this);
  }

  public FontSizeOptions() {
    this(AdaptiveCardObjectModelJNI.new_FontSizeOptions(), true);
  }

}
