/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class TextColor {
  public final static TextColor Default = new TextColor("Default", AdaptiveCardObjectModelJNI.TextColor_Default_get());
  public final static TextColor Dark = new TextColor("Dark");
  public final static TextColor Light = new TextColor("Light");
  public final static TextColor Accent = new TextColor("Accent");
  public final static TextColor Good = new TextColor("Good");
  public final static TextColor Warning = new TextColor("Warning");
  public final static TextColor Attention = new TextColor("Attention");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextColor swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextColor.class + " with value " + swigValue);
  }

  private TextColor(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextColor(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextColor(String swigName, TextColor swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextColor[] swigValues = { Default, Dark, Light, Accent, Good, Warning, Attention };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

