/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class TextSize {
  public final static TextSize Small = new TextSize("Small", AdaptiveCardObjectModelJNI.TextSize_Small_get());
  public final static TextSize Normal = new TextSize("Normal");
  public final static TextSize Medium = new TextSize("Medium");
  public final static TextSize Large = new TextSize("Large");
  public final static TextSize ExtraLarge = new TextSize("ExtraLarge");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextSize swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextSize.class + " with value " + swigValue);
  }

  private TextSize(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextSize(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextSize(String swigName, TextSize swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextSize[] swigValues = { Small, Normal, Medium, Large, ExtraLarge };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

