/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class ActionAlignment {
  public final static ActionAlignment Left = new ActionAlignment("Left", AdaptiveCardObjectModelJNI.ActionAlignment_Left_get());
  public final static ActionAlignment Center = new ActionAlignment("Center");
  public final static ActionAlignment Right = new ActionAlignment("Right");
  public final static ActionAlignment Stretch = new ActionAlignment("Stretch");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ActionAlignment swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ActionAlignment.class + " with value " + swigValue);
  }

  private ActionAlignment(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ActionAlignment(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ActionAlignment(String swigName, ActionAlignment swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ActionAlignment[] swigValues = { Left, Center, Right, Stretch };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

