/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class ColorOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ColorOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColorOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ColorOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDefaultColor(ColorOption value) {
    AdaptiveCardObjectModelJNI.ColorOptions_defaultColor_set(swigCPtr, this, ColorOption.getCPtr(value), value);
  }

  public ColorOption getDefaultColor() {
    long cPtr = AdaptiveCardObjectModelJNI.ColorOptions_defaultColor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorOption(cPtr, false);
  }

  public void setAccent(ColorOption value) {
    AdaptiveCardObjectModelJNI.ColorOptions_accent_set(swigCPtr, this, ColorOption.getCPtr(value), value);
  }

  public ColorOption getAccent() {
    long cPtr = AdaptiveCardObjectModelJNI.ColorOptions_accent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorOption(cPtr, false);
  }

  public void setDark(ColorOption value) {
    AdaptiveCardObjectModelJNI.ColorOptions_dark_set(swigCPtr, this, ColorOption.getCPtr(value), value);
  }

  public ColorOption getDark() {
    long cPtr = AdaptiveCardObjectModelJNI.ColorOptions_dark_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorOption(cPtr, false);
  }

  public void setLight(ColorOption value) {
    AdaptiveCardObjectModelJNI.ColorOptions_light_set(swigCPtr, this, ColorOption.getCPtr(value), value);
  }

  public ColorOption getLight() {
    long cPtr = AdaptiveCardObjectModelJNI.ColorOptions_light_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorOption(cPtr, false);
  }

  public void setGood(ColorOption value) {
    AdaptiveCardObjectModelJNI.ColorOptions_good_set(swigCPtr, this, ColorOption.getCPtr(value), value);
  }

  public ColorOption getGood() {
    long cPtr = AdaptiveCardObjectModelJNI.ColorOptions_good_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorOption(cPtr, false);
  }

  public void setWarning(ColorOption value) {
    AdaptiveCardObjectModelJNI.ColorOptions_warning_set(swigCPtr, this, ColorOption.getCPtr(value), value);
  }

  public ColorOption getWarning() {
    long cPtr = AdaptiveCardObjectModelJNI.ColorOptions_warning_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorOption(cPtr, false);
  }

  public void setAttention(ColorOption value) {
    AdaptiveCardObjectModelJNI.ColorOptions_attention_set(swigCPtr, this, ColorOption.getCPtr(value), value);
  }

  public ColorOption getAttention() {
    long cPtr = AdaptiveCardObjectModelJNI.ColorOptions_attention_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ColorOption(cPtr, false);
  }

  public ColorOptions() {
    this(AdaptiveCardObjectModelJNI.new_ColorOptions(), true);
  }

}
