/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class Color {
  public final static Color Default = new Color("Default", AdaptiveCardObjectModelJNI.Color_Default_get());
  public final static Color Dark = new Color("Dark");
  public final static Color Light = new Color("Light");
  public final static Color Accent = new Color("Accent");
  public final static Color Good = new Color("Good");
  public final static Color Warning = new Color("Warning");
  public final static Color Attention = new Color("Attention");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Color swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Color.class + " with value " + swigValue);
  }

  private Color(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Color(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Color(String swigName, Color swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Color[] swigValues = { Default, Dark, Light, Accent, Good, Warning, Attention };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

