/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class ColumnSetConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ColumnSetConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColumnSetConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ColumnSetConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSeparation(SeparationConfig value) {
    AdaptiveCardObjectModelJNI.ColumnSetConfig_separation_set(swigCPtr, this, SeparationConfig.getCPtr(value), value);
  }

  public SeparationConfig getSeparation() {
    long cPtr = AdaptiveCardObjectModelJNI.ColumnSetConfig_separation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SeparationConfig(cPtr, false);
  }

  public static ColumnSetConfig Deserialize(SWIGTYPE_p_Json__Value json, ColumnSetConfig defaultValue) {
    return new ColumnSetConfig(AdaptiveCardObjectModelJNI.ColumnSetConfig_Deserialize(SWIGTYPE_p_Json__Value.getCPtr(json), ColumnSetConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public ColumnSetConfig() {
    this(AdaptiveCardObjectModelJNI.new_ColumnSetConfig(), true);
  }

}
