/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class ColumnVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ColumnVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColumnVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ColumnVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ColumnVector() {
    this(AdaptiveCardObjectModelJNI.new_ColumnVector__SWIG_0(), true);
  }

  public ColumnVector(long n) {
    this(AdaptiveCardObjectModelJNI.new_ColumnVector__SWIG_1(n), true);
  }

  public long size() {
    return AdaptiveCardObjectModelJNI.ColumnVector_size(swigCPtr, this);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.ColumnVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.ColumnVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.ColumnVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.ColumnVector_clear(swigCPtr, this);
  }

  public void add(Column x) {
    AdaptiveCardObjectModelJNI.ColumnVector_add(swigCPtr, this, Column.getCPtr(x), x);
  }

  public Column get(int i) {
    long cPtr = AdaptiveCardObjectModelJNI.ColumnVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Column(cPtr, true);
  }

  public void set(int i, Column val) {
    AdaptiveCardObjectModelJNI.ColumnVector_set(swigCPtr, this, i, Column.getCPtr(val), val);
  }

}
