/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class ContainerStyle {
  public final static ContainerStyle Normal = new ContainerStyle("Normal", AdaptiveCardObjectModelJNI.ContainerStyle_Normal_get());
  public final static ContainerStyle Emphasis = new ContainerStyle("Emphasis");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ContainerStyle swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ContainerStyle.class + " with value " + swigValue);
  }

  private ContainerStyle(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ContainerStyle(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ContainerStyle(String swigName, ContainerStyle swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ContainerStyle[] swigValues = { Normal, Emphasis };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

