/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class ContainerStyleConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContainerStyleConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContainerStyleConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ContainerStyleConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBackgroundColor(String value) {
    AdaptiveCardObjectModelJNI.ContainerStyleConfig_backgroundColor_set(swigCPtr, this, value);
  }

  public String getBackgroundColor() {
    return AdaptiveCardObjectModelJNI.ContainerStyleConfig_backgroundColor_get(swigCPtr, this);
  }

  public void setBorderColor(String value) {
    AdaptiveCardObjectModelJNI.ContainerStyleConfig_borderColor_set(swigCPtr, this, value);
  }

  public String getBorderColor() {
    return AdaptiveCardObjectModelJNI.ContainerStyleConfig_borderColor_get(swigCPtr, this);
  }

  public void setBorderThickness(SpacingDefinition value) {
    AdaptiveCardObjectModelJNI.ContainerStyleConfig_borderThickness_set(swigCPtr, this, SpacingDefinition.getCPtr(value), value);
  }

  public SpacingDefinition getBorderThickness() {
    long cPtr = AdaptiveCardObjectModelJNI.ContainerStyleConfig_borderThickness_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SpacingDefinition(cPtr, false);
  }

  public void setPadding(SpacingDefinition value) {
    AdaptiveCardObjectModelJNI.ContainerStyleConfig_padding_set(swigCPtr, this, SpacingDefinition.getCPtr(value), value);
  }

  public SpacingDefinition getPadding() {
    long cPtr = AdaptiveCardObjectModelJNI.ContainerStyleConfig_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SpacingDefinition(cPtr, false);
  }

  public static ContainerStyleConfig Deserialize(SWIGTYPE_p_Json__Value json, ContainerStyleConfig defaultValue) {
    return new ContainerStyleConfig(AdaptiveCardObjectModelJNI.ContainerStyleConfig_Deserialize(SWIGTYPE_p_Json__Value.getCPtr(json), ContainerStyleConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public ContainerStyleConfig() {
    this(AdaptiveCardObjectModelJNI.new_ContainerStyleConfig(), true);
  }

}
