/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class FontSizesConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FontSizesConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FontSizesConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_FontSizesConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSmallFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizesConfig_smallFontSize_set(swigCPtr, this, value);
  }

  public long getSmallFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizesConfig_smallFontSize_get(swigCPtr, this);
  }

  public void setDefaultFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizesConfig_defaultFontSize_set(swigCPtr, this, value);
  }

  public long getDefaultFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizesConfig_defaultFontSize_get(swigCPtr, this);
  }

  public void setMediumFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizesConfig_mediumFontSize_set(swigCPtr, this, value);
  }

  public long getMediumFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizesConfig_mediumFontSize_get(swigCPtr, this);
  }

  public void setLargeFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizesConfig_largeFontSize_set(swigCPtr, this, value);
  }

  public long getLargeFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizesConfig_largeFontSize_get(swigCPtr, this);
  }

  public void setExtraLargeFontSize(long value) {
    AdaptiveCardObjectModelJNI.FontSizesConfig_extraLargeFontSize_set(swigCPtr, this, value);
  }

  public long getExtraLargeFontSize() {
    return AdaptiveCardObjectModelJNI.FontSizesConfig_extraLargeFontSize_get(swigCPtr, this);
  }

  public static FontSizesConfig Deserialize(SWIGTYPE_p_Json__Value json, FontSizesConfig defaultValue) {
    return new FontSizesConfig(AdaptiveCardObjectModelJNI.FontSizesConfig_Deserialize(SWIGTYPE_p_Json__Value.getCPtr(json), FontSizesConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public FontSizesConfig() {
    this(AdaptiveCardObjectModelJNI.new_FontSizesConfig(), true);
  }

}
