/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class FontWeightsConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FontWeightsConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FontWeightsConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_FontWeightsConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLighterWeight(long value) {
    AdaptiveCardObjectModelJNI.FontWeightsConfig_lighterWeight_set(swigCPtr, this, value);
  }

  public long getLighterWeight() {
    return AdaptiveCardObjectModelJNI.FontWeightsConfig_lighterWeight_get(swigCPtr, this);
  }

  public void setDefaultWeight(long value) {
    AdaptiveCardObjectModelJNI.FontWeightsConfig_defaultWeight_set(swigCPtr, this, value);
  }

  public long getDefaultWeight() {
    return AdaptiveCardObjectModelJNI.FontWeightsConfig_defaultWeight_get(swigCPtr, this);
  }

  public void setBolderWeight(long value) {
    AdaptiveCardObjectModelJNI.FontWeightsConfig_bolderWeight_set(swigCPtr, this, value);
  }

  public long getBolderWeight() {
    return AdaptiveCardObjectModelJNI.FontWeightsConfig_bolderWeight_get(swigCPtr, this);
  }

  public static FontWeightsConfig Deserialize(SWIGTYPE_p_Json__Value json, FontWeightsConfig defaultValue) {
    return new FontWeightsConfig(AdaptiveCardObjectModelJNI.FontWeightsConfig_Deserialize(SWIGTYPE_p_Json__Value.getCPtr(json), FontWeightsConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public FontWeightsConfig() {
    this(AdaptiveCardObjectModelJNI.new_FontWeightsConfig(), true);
  }

}
