/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class ForegroundColor {
  public final static ForegroundColor Default = new ForegroundColor("Default", AdaptiveCardObjectModelJNI.ForegroundColor_Default_get());
  public final static ForegroundColor Dark = new ForegroundColor("Dark");
  public final static ForegroundColor Light = new ForegroundColor("Light");
  public final static ForegroundColor Accent = new ForegroundColor("Accent");
  public final static ForegroundColor Good = new ForegroundColor("Good");
  public final static ForegroundColor Warning = new ForegroundColor("Warning");
  public final static ForegroundColor Attention = new ForegroundColor("Attention");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ForegroundColor swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ForegroundColor.class + " with value " + swigValue);
  }

  private ForegroundColor(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ForegroundColor(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ForegroundColor(String swigName, ForegroundColor swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ForegroundColor[] swigValues = { Default, Dark, Light, Accent, Good, Warning, Attention };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

