/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class HttpAction extends BaseActionElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected HttpAction(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.HttpAction_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HttpAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_HttpAction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HttpAction() {
    this(AdaptiveCardObjectModelJNI.new_HttpAction(), true);
  }

  public static HttpAction Deserialize(SWIGTYPE_p_Json__Value root) {
    long cPtr = AdaptiveCardObjectModelJNI.HttpAction_Deserialize(SWIGTYPE_p_Json__Value.getCPtr(root));
    return (cPtr == 0) ? null : new HttpAction(cPtr, true);
  }

  public static HttpAction DeserializeFromString(String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.HttpAction_DeserializeFromString(jsonString);
    return (cPtr == 0) ? null : new HttpAction(cPtr, true);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.HttpAction_Serialize(swigCPtr, this);
  }

  public SWIGTYPE_p_Json__Value SerializeToJsonValue() {
    return new SWIGTYPE_p_Json__Value(AdaptiveCardObjectModelJNI.HttpAction_SerializeToJsonValue(swigCPtr, this), true);
  }

  public String GetUrl() {
    return AdaptiveCardObjectModelJNI.HttpAction_GetUrl(swigCPtr, this);
  }

  public void SetUrl(String value) {
    AdaptiveCardObjectModelJNI.HttpAction_SetUrl(swigCPtr, this, value);
  }

  public String GetMethod() {
    return AdaptiveCardObjectModelJNI.HttpAction_GetMethod(swigCPtr, this);
  }

  public void SetMethod(String value) {
    AdaptiveCardObjectModelJNI.HttpAction_SetMethod(swigCPtr, this, value);
  }

  public String GetBody() {
    return AdaptiveCardObjectModelJNI.HttpAction_GetBody(swigCPtr, this);
  }

  public void SetBody(String value) {
    AdaptiveCardObjectModelJNI.HttpAction_SetBody(swigCPtr, this, value);
  }

  public static HttpAction dynamic_cast(BaseActionElement baseActionElement) {
    long cPtr = AdaptiveCardObjectModelJNI.HttpAction_dynamic_cast(BaseActionElement.getCPtr(baseActionElement), baseActionElement);
    return (cPtr == 0) ? null : new HttpAction(cPtr, true);
  }

}
