/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class InputChoice {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InputChoice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InputChoice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_InputChoice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InputChoice() {
    this(AdaptiveCardObjectModelJNI.new_InputChoice(), true);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.InputChoice_Serialize(swigCPtr, this);
  }

  public String GetTitle() {
    return AdaptiveCardObjectModelJNI.InputChoice_GetTitle(swigCPtr, this);
  }

  public void SetTitle(String value) {
    AdaptiveCardObjectModelJNI.InputChoice_SetTitle(swigCPtr, this, value);
  }

  public String GetValue() {
    return AdaptiveCardObjectModelJNI.InputChoice_GetValue(swigCPtr, this);
  }

  public void SetValue(String value) {
    AdaptiveCardObjectModelJNI.InputChoice_SetValue(swigCPtr, this, value);
  }

  public boolean GetIsSelected() {
    return AdaptiveCardObjectModelJNI.InputChoice_GetIsSelected(swigCPtr, this);
  }

  public void SetIsSelected(boolean value) {
    AdaptiveCardObjectModelJNI.InputChoice_SetIsSelected(swigCPtr, this, value);
  }

  public String GetSpeak() {
    return AdaptiveCardObjectModelJNI.InputChoice_GetSpeak(swigCPtr, this);
  }

  public void SetSpeak(String value) {
    AdaptiveCardObjectModelJNI.InputChoice_SetSpeak(swigCPtr, this, value);
  }

  public static SWIGTYPE_p_std__shared_ptrT_AdaptiveCards__InputChoice_t Deserialize(SWIGTYPE_p_Json__Value root) {
    return new SWIGTYPE_p_std__shared_ptrT_AdaptiveCards__InputChoice_t(AdaptiveCardObjectModelJNI.InputChoice_Deserialize(SWIGTYPE_p_Json__Value.getCPtr(root)), true);
  }

  public static SWIGTYPE_p_std__shared_ptrT_AdaptiveCards__InputChoice_t DeserializeFromString(String jsonString) {
    return new SWIGTYPE_p_std__shared_ptrT_AdaptiveCards__InputChoice_t(AdaptiveCardObjectModelJNI.InputChoice_DeserializeFromString(jsonString), true);
  }

}
