/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public class SeparatorThicknessConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SeparatorThicknessConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SeparatorThicknessConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_SeparatorThicknessConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDefaultSeparatorThickness(long value) {
    AdaptiveCardObjectModelJNI.SeparatorThicknessConfig_defaultSeparatorThickness_set(swigCPtr, this, value);
  }

  public long getDefaultSeparatorThickness() {
    return AdaptiveCardObjectModelJNI.SeparatorThicknessConfig_defaultSeparatorThickness_get(swigCPtr, this);
  }

  public void setThickSeparatorThickness(long value) {
    AdaptiveCardObjectModelJNI.SeparatorThicknessConfig_thickSeparatorThickness_set(swigCPtr, this, value);
  }

  public long getThickSeparatorThickness() {
    return AdaptiveCardObjectModelJNI.SeparatorThicknessConfig_thickSeparatorThickness_get(swigCPtr, this);
  }

  public static SeparatorThicknessConfig Deserialize(SWIGTYPE_p_Json__Value json, SeparatorThicknessConfig defaultValue) {
    return new SeparatorThicknessConfig(AdaptiveCardObjectModelJNI.SeparatorThicknessConfig_Deserialize(SWIGTYPE_p_Json__Value.getCPtr(json), SeparatorThicknessConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public SeparatorThicknessConfig() {
    this(AdaptiveCardObjectModelJNI.new_SeparatorThicknessConfig(), true);
  }

}
