/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class TextSectionFormat {
  public final static TextSectionFormat RegularString = new TextSectionFormat("RegularString", AdaptiveCardObjectModelJNI.TextSectionFormat_RegularString_get());
  public final static TextSectionFormat Time = new TextSectionFormat("Time");
  public final static TextSectionFormat DateCompact = new TextSectionFormat("DateCompact");
  public final static TextSectionFormat DateShort = new TextSectionFormat("DateShort");
  public final static TextSectionFormat DateLong = new TextSectionFormat("DateLong");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextSectionFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextSectionFormat.class + " with value " + swigValue);
  }

  private TextSectionFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextSectionFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextSectionFormat(String swigName, TextSectionFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextSectionFormat[] swigValues = { RegularString, Time, DateCompact, DateShort, DateLong };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

