/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ActionSet extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ActionSet(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.ActionSet_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ActionSet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_ActionSet(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ActionSet() {
    this(AdaptiveCardObjectModelJNI.new_ActionSet__SWIG_0(), true);
  }

  public ActionSet(Spacing spacing, boolean separator) {
    this(AdaptiveCardObjectModelJNI.new_ActionSet__SWIG_1(spacing.swigValue(), separator), true);
  }

  public ActionSet(Spacing spacing, boolean separator, BaseActionElementVector actions) {
    this(AdaptiveCardObjectModelJNI.new_ActionSet__SWIG_2(spacing.swigValue(), separator, BaseActionElementVector.getCPtr(actions), actions), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.ActionSet_SerializeToJsonValue(swigCPtr, this), true);
  }

  public ActionsOrientation GetOrientation() {
    return ActionsOrientation.swigToEnum(AdaptiveCardObjectModelJNI.ActionSet_GetOrientation(swigCPtr, this));
  }

  public void SetOrientation(ActionsOrientation value) {
    AdaptiveCardObjectModelJNI.ActionSet_SetOrientation(swigCPtr, this, value.swigValue());
  }

  public BaseActionElementVector GetActions() {
    return new BaseActionElementVector(AdaptiveCardObjectModelJNI.ActionSet_GetActions(swigCPtr, this), false);
  }

  public static ActionSet dynamic_cast(BaseCardElement baseActionElement) {
    long cPtr = AdaptiveCardObjectModelJNI.ActionSet_dynamic_cast(BaseCardElement.getCPtr(baseActionElement), baseActionElement);
    return (cPtr == 0) ? null : new ActionSet(cPtr, true);
  }

}
