/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class AuthCardButton {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected AuthCardButton(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AuthCardButton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_AuthCardButton(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AuthCardButton() {
    this(AdaptiveCardObjectModelJNI.new_AuthCardButton__SWIG_0(), true);
  }

  public AuthCardButton(String type, String title, String image, String value) {
    this(AdaptiveCardObjectModelJNI.new_AuthCardButton__SWIG_1(type, title, image, value), true);
  }

  public String GetType() {
    return AdaptiveCardObjectModelJNI.AuthCardButton_GetType__SWIG_0(swigCPtr, this);
  }

  public void SetType(String arg0) {
    AdaptiveCardObjectModelJNI.AuthCardButton_SetType(swigCPtr, this, arg0);
  }

  public String GetTitle() {
    return AdaptiveCardObjectModelJNI.AuthCardButton_GetTitle__SWIG_0(swigCPtr, this);
  }

  public void SetTitle(String arg0) {
    AdaptiveCardObjectModelJNI.AuthCardButton_SetTitle(swigCPtr, this, arg0);
  }

  public String GetImage() {
    return AdaptiveCardObjectModelJNI.AuthCardButton_GetImage__SWIG_0(swigCPtr, this);
  }

  public void SetImage(String arg0) {
    AdaptiveCardObjectModelJNI.AuthCardButton_SetImage(swigCPtr, this, arg0);
  }

  public String GetValue() {
    return AdaptiveCardObjectModelJNI.AuthCardButton_GetValue__SWIG_0(swigCPtr, this);
  }

  public void SetValue(String arg0) {
    AdaptiveCardObjectModelJNI.AuthCardButton_SetValue(swigCPtr, this, arg0);
  }

  public boolean ShouldSerialize() {
    return AdaptiveCardObjectModelJNI.AuthCardButton_ShouldSerialize(swigCPtr, this);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.AuthCardButton_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.AuthCardButton_SerializeToJsonValue(swigCPtr, this), true);
  }

  public static AuthCardButton Deserialize(ParseContext context, JsonValue json) {
    long cPtr = AdaptiveCardObjectModelJNI.AuthCardButton_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(json), json);
    return (cPtr == 0) ? null : new AuthCardButton(cPtr, true);
  }

  public static AuthCardButton DeserializeFromString(ParseContext context, String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.AuthCardButton_DeserializeFromString(ParseContext.getCPtr(context), context, jsonString);
    return (cPtr == 0) ? null : new AuthCardButton(cPtr, true);
  }

}
