/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class BaseElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected BaseElement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BaseElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_BaseElement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigSetCMemOwn(false);
    delete();
  }

  public void swigReleaseOwnership() {
    swigSetCMemOwn(false);
    AdaptiveCardObjectModelJNI.BaseElement_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigSetCMemOwn(true);
    AdaptiveCardObjectModelJNI.BaseElement_change_ownership(this, swigCPtr, true);
  }

  public BaseElement() {
    this(AdaptiveCardObjectModelJNI.new_BaseElement__SWIG_0(), true);
    AdaptiveCardObjectModelJNI.BaseElement_director_connect(this, swigCPtr, true, true);
  }

  public BaseElement(BaseElement arg0) {
    this(AdaptiveCardObjectModelJNI.new_BaseElement__SWIG_1(BaseElement.getCPtr(arg0), arg0), true);
    AdaptiveCardObjectModelJNI.BaseElement_director_connect(this, swigCPtr, true, true);
  }

  public String GetElementTypeString() {
    return AdaptiveCardObjectModelJNI.BaseElement_GetElementTypeString(swigCPtr, this);
  }

  public void SetElementTypeString(String value) {
    AdaptiveCardObjectModelJNI.BaseElement_SetElementTypeString(swigCPtr, this, value);
  }

  public String GetId() {
    return (getClass() == BaseElement.class) ? AdaptiveCardObjectModelJNI.BaseElement_GetId(swigCPtr, this) : AdaptiveCardObjectModelJNI.BaseElement_GetIdSwigExplicitBaseElement(swigCPtr, this);
  }

  public void SetId(String value) {
    if (getClass() == BaseElement.class) AdaptiveCardObjectModelJNI.BaseElement_SetId(swigCPtr, this, value); else AdaptiveCardObjectModelJNI.BaseElement_SetIdSwigExplicitBaseElement(swigCPtr, this, value);
  }

  public InternalId GetInternalId() {
    return new InternalId(AdaptiveCardObjectModelJNI.BaseElement_GetInternalId(swigCPtr, this), true);
  }

  public String Serialize() {
    return (getClass() == BaseElement.class) ? AdaptiveCardObjectModelJNI.BaseElement_Serialize(swigCPtr, this) : AdaptiveCardObjectModelJNI.BaseElement_SerializeSwigExplicitBaseElement(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue((getClass() == BaseElement.class) ? AdaptiveCardObjectModelJNI.BaseElement_SerializeToJsonValue(swigCPtr, this) : AdaptiveCardObjectModelJNI.BaseElement_SerializeToJsonValueSwigExplicitBaseElement(swigCPtr, this), true);
  }

  public JsonValue GetAdditionalProperties() {
    return new JsonValue(AdaptiveCardObjectModelJNI.BaseElement_GetAdditionalProperties(swigCPtr, this), false);
  }

  public void SetAdditionalProperties(JsonValue additionalProperties) {
    AdaptiveCardObjectModelJNI.BaseElement_SetAdditionalProperties__SWIG_0(swigCPtr, this, JsonValue.getCPtr(additionalProperties), additionalProperties);
  }

  public FallbackType GetFallbackType() {
    return FallbackType.swigToEnum(AdaptiveCardObjectModelJNI.BaseElement_GetFallbackType(swigCPtr, this));
  }

  public BaseElement GetFallbackContent() {
    long cPtr = AdaptiveCardObjectModelJNI.BaseElement_GetFallbackContent(swigCPtr, this);
    return (cPtr == 0) ? null : new BaseElement(cPtr, true);
  }

  public boolean CanFallbackToAncestor() {
    return AdaptiveCardObjectModelJNI.BaseElement_CanFallbackToAncestor(swigCPtr, this);
  }

  public void SetFallbackType(FallbackType type) {
    AdaptiveCardObjectModelJNI.BaseElement_SetFallbackType(swigCPtr, this, type.swigValue());
  }

  public void SetFallbackContent(BaseElement element) {
    AdaptiveCardObjectModelJNI.BaseElement_SetFallbackContent(swigCPtr, this, BaseElement.getCPtr(element), element);
  }

  public boolean MeetsRequirements(FeatureRegistration hostProvides) {
    return AdaptiveCardObjectModelJNI.BaseElement_MeetsRequirements(swigCPtr, this, FeatureRegistration.getCPtr(hostProvides), hostProvides);
  }

  public SWIGTYPE_p_std__unordered_mapT_std__string_AdaptiveCards__SemanticVersion_t GetRequirements() {
    return new SWIGTYPE_p_std__unordered_mapT_std__string_AdaptiveCards__SemanticVersion_t(AdaptiveCardObjectModelJNI.BaseElement_GetRequirements__SWIG_0(swigCPtr, this), false);
  }

  public void GetResourceInformation(RemoteResourceInformationVector resourceUris) {
    if (getClass() == BaseElement.class) AdaptiveCardObjectModelJNI.BaseElement_GetResourceInformation(swigCPtr, this, RemoteResourceInformationVector.getCPtr(resourceUris), resourceUris); else AdaptiveCardObjectModelJNI.BaseElement_GetResourceInformationSwigExplicitBaseElement(swigCPtr, this, RemoteResourceInformationVector.getCPtr(resourceUris), resourceUris);
  }

}
