/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ColumnVector extends java.util.AbstractList<Column> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ColumnVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ColumnVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ColumnVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ColumnVector(Column[] initialElements) {
    this();
    for (Column element : initialElements) {
      add(element);
    }
  }

  public ColumnVector(Iterable<Column> initialElements) {
    this();
    for (Column element : initialElements) {
      add(element);
    }
  }

  public Column get(int index) {
    return doGet(index);
  }

  public Column set(int index, Column e) {
    return doSet(index, e);
  }

  public boolean add(Column e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Column e) {
    modCount++;
    doAdd(index, e);
  }

  public Column remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public ColumnVector() {
    this(AdaptiveCardObjectModelJNI.new_ColumnVector__SWIG_0(), true);
  }

  public ColumnVector(ColumnVector other) {
    this(AdaptiveCardObjectModelJNI.new_ColumnVector__SWIG_1(ColumnVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.ColumnVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.ColumnVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.ColumnVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.ColumnVector_clear(swigCPtr, this);
  }

  public ColumnVector(int count, Column value) {
    this(AdaptiveCardObjectModelJNI.new_ColumnVector__SWIG_2(count, Column.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.ColumnVector_doSize(swigCPtr, this);
  }

  private void doAdd(Column x) {
    AdaptiveCardObjectModelJNI.ColumnVector_doAdd__SWIG_0(swigCPtr, this, Column.getCPtr(x), x);
  }

  private void doAdd(int index, Column x) {
    AdaptiveCardObjectModelJNI.ColumnVector_doAdd__SWIG_1(swigCPtr, this, index, Column.getCPtr(x), x);
  }

  private Column doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.ColumnVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Column(cPtr, true);
  }

  private Column doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.ColumnVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Column(cPtr, true);
  }

  private Column doSet(int index, Column val) {
    long cPtr = AdaptiveCardObjectModelJNI.ColumnVector_doSet(swigCPtr, this, index, Column.getCPtr(val), val);
    return (cPtr == 0) ? null : new Column(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.ColumnVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
