/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum ContainerStyle {
  None,
  Default,
  Emphasis,
  Good,
  Attention,
  Warning,
  Accent;

  public final int swigValue() {
    return swigValue;
  }

  public static ContainerStyle swigToEnum(int swigValue) {
    ContainerStyle[] swigValues = ContainerStyle.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ContainerStyle swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ContainerStyle.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ContainerStyle() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ContainerStyle(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ContainerStyle(ContainerStyle swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

