/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class HighlightColorConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HighlightColorConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HighlightColorConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_HighlightColorConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDefaultColor(String value) {
    AdaptiveCardObjectModelJNI.HighlightColorConfig_defaultColor_set(swigCPtr, this, value);
  }

  public String getDefaultColor() {
    return AdaptiveCardObjectModelJNI.HighlightColorConfig_defaultColor_get(swigCPtr, this);
  }

  public void setSubtleColor(String value) {
    AdaptiveCardObjectModelJNI.HighlightColorConfig_subtleColor_set(swigCPtr, this, value);
  }

  public String getSubtleColor() {
    return AdaptiveCardObjectModelJNI.HighlightColorConfig_subtleColor_get(swigCPtr, this);
  }

  public static HighlightColorConfig Deserialize(JsonValue json, HighlightColorConfig defaultValue) {
    return new HighlightColorConfig(AdaptiveCardObjectModelJNI.HighlightColorConfig_Deserialize(JsonValue.getCPtr(json), json, HighlightColorConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public HighlightColorConfig() {
    this(AdaptiveCardObjectModelJNI.new_HighlightColorConfig(), true);
  }

}
