/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class Image extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected Image(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.Image_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_Image(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Image() {
    this(AdaptiveCardObjectModelJNI.new_Image(), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.Image_SerializeToJsonValue(swigCPtr, this), true);
  }

  public String GetUrl() {
    return AdaptiveCardObjectModelJNI.Image_GetUrl(swigCPtr, this);
  }

  public void SetUrl(String value) {
    AdaptiveCardObjectModelJNI.Image_SetUrl(swigCPtr, this, value);
  }

  public ImageStyle GetImageStyle() {
    return ImageStyle.swigToEnum(AdaptiveCardObjectModelJNI.Image_GetImageStyle(swigCPtr, this));
  }

  public void SetImageStyle(ImageStyle value) {
    AdaptiveCardObjectModelJNI.Image_SetImageStyle(swigCPtr, this, value.swigValue());
  }

  public ImageSize GetImageSize() {
    return ImageSize.swigToEnum(AdaptiveCardObjectModelJNI.Image_GetImageSize(swigCPtr, this));
  }

  public void SetImageSize(ImageSize value) {
    AdaptiveCardObjectModelJNI.Image_SetImageSize(swigCPtr, this, value.swigValue());
  }

  public String GetAltText() {
    return AdaptiveCardObjectModelJNI.Image_GetAltText(swigCPtr, this);
  }

  public void SetAltText(String value) {
    AdaptiveCardObjectModelJNI.Image_SetAltText(swigCPtr, this, value);
  }

  public HorizontalAlignment GetHorizontalAlignment() {
    return HorizontalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.Image_GetHorizontalAlignment(swigCPtr, this));
  }

  public void SetHorizontalAlignment(HorizontalAlignment value) {
    AdaptiveCardObjectModelJNI.Image_SetHorizontalAlignment(swigCPtr, this, value.swigValue());
  }

  public BaseActionElement GetSelectAction() {
    long cPtr = AdaptiveCardObjectModelJNI.Image_GetSelectAction(swigCPtr, this);
    return (cPtr == 0) ? null : new BaseActionElement(cPtr, true);
  }

  public void SetSelectAction(BaseActionElement action) {
    AdaptiveCardObjectModelJNI.Image_SetSelectAction(swigCPtr, this, BaseActionElement.getCPtr(action), action);
  }

  public long GetWidth() {
    return AdaptiveCardObjectModelJNI.Image_GetWidth(swigCPtr, this);
  }

  public void SetWidth(long value) {
    AdaptiveCardObjectModelJNI.Image_SetWidth(swigCPtr, this, value);
  }

  public long GetHeight() {
    return AdaptiveCardObjectModelJNI.Image_GetHeight(swigCPtr, this);
  }

  public void SetHeight(long value) {
    AdaptiveCardObjectModelJNI.Image_SetHeight(swigCPtr, this, value);
  }

  public void GetResourceUris(StringVector resourceUris) {
    AdaptiveCardObjectModelJNI.Image_GetResourceUris(swigCPtr, this, StringVector.getCPtr(resourceUris), resourceUris);
  }

  public static Image dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.Image_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new Image(cPtr, true);
  }

}
