/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class MediaSource extends ContentSource {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected MediaSource(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.MediaSource_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MediaSource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_MediaSource(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MediaSource() {
    this(AdaptiveCardObjectModelJNI.new_MediaSource(), true);
  }

}
