/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ParagraphVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParagraphVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParagraphVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ParagraphVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParagraphVector() {
    this(AdaptiveCardObjectModelJNI.new_ParagraphVector__SWIG_0(), true);
  }

  public ParagraphVector(long n) {
    this(AdaptiveCardObjectModelJNI.new_ParagraphVector__SWIG_1(n), true);
  }

  public long size() {
    return AdaptiveCardObjectModelJNI.ParagraphVector_size(swigCPtr, this);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.ParagraphVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.ParagraphVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.ParagraphVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.ParagraphVector_clear(swigCPtr, this);
  }

  public void add(Paragraph x) {
    AdaptiveCardObjectModelJNI.ParagraphVector_add(swigCPtr, this, Paragraph.getCPtr(x), x);
  }

  public Paragraph get(int i) {
    long cPtr = AdaptiveCardObjectModelJNI.ParagraphVector_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Paragraph(cPtr, true);
  }

  public void set(int i, Paragraph val) {
    AdaptiveCardObjectModelJNI.ParagraphVector_set(swigCPtr, this, i, Paragraph.getCPtr(val), val);
  }

}
