/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum Sentiment {
  Default(0),
  Positive,
  Destructive;

  public final int swigValue() {
    return swigValue;
  }

  public static Sentiment swigToEnum(int swigValue) {
    Sentiment[] swigValues = Sentiment.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Sentiment swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Sentiment.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Sentiment() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Sentiment(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Sentiment(Sentiment swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

