/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum Spacing {
  Default(0),
  None,
  Small,
  Medium,
  Large,
  ExtraLarge,
  Padding;

  public final int swigValue() {
    return swigValue;
  }

  public static Spacing swigToEnum(int swigValue) {
    Spacing[] swigValues = Spacing.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Spacing swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Spacing.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Spacing() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Spacing(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Spacing(Spacing swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

