/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public final class Spacing {
  public final static Spacing Default = new Spacing("Default", AdaptiveCardObjectModelJNI.Spacing_Default_get());
  public final static Spacing None = new Spacing("None");
  public final static Spacing Small = new Spacing("Small");
  public final static Spacing Medium = new Spacing("Medium");
  public final static Spacing Large = new Spacing("Large");
  public final static Spacing ExtraLarge = new Spacing("ExtraLarge");
  public final static Spacing Padding = new Spacing("Padding");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Spacing swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Spacing.class + " with value " + swigValue);
  }

  private Spacing(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Spacing(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Spacing(String swigName, Spacing swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Spacing[] swigValues = { Default, None, Small, Medium, Large, ExtraLarge, Padding };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

