/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class TableRow extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected TableRow(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.TableRow_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TableRow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_TableRow(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TableRow() {
    this(AdaptiveCardObjectModelJNI.new_TableRow__SWIG_0(), true);
  }

  public TableRow(TableRow arg0) {
    this(AdaptiveCardObjectModelJNI.new_TableRow__SWIG_1(TableRow.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.TableRow_SerializeToJsonValue(swigCPtr, this), true);
  }

  public TableCellVector GetCells() {
    return new TableCellVector(AdaptiveCardObjectModelJNI.TableRow_GetCells__SWIG_0(swigCPtr, this), false);
  }

  public void SetCells(TableCellVector value) {
    AdaptiveCardObjectModelJNI.TableRow_SetCells(swigCPtr, this, TableCellVector.getCPtr(value), value);
  }

  public VerticalContentAlignment GetVerticalCellContentAlignment() {
    return VerticalContentAlignment.swigToEnum(AdaptiveCardObjectModelJNI.TableRow_GetVerticalCellContentAlignment(swigCPtr, this));
  }

  public void SetVerticalCellContentAlignment(VerticalContentAlignment value) {
    AdaptiveCardObjectModelJNI.TableRow_SetVerticalCellContentAlignment(swigCPtr, this, value.swigValue());
  }

  public HorizontalAlignment GetHorizontalCellContentAlignment() {
    return HorizontalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.TableRow_GetHorizontalCellContentAlignment(swigCPtr, this));
  }

  public void SetHorizontalCellContentAlignment(HorizontalAlignment value) {
    AdaptiveCardObjectModelJNI.TableRow_SetHorizontalCellContentAlignment(swigCPtr, this, value.swigValue());
  }

  public ContainerStyle GetStyle() {
    return ContainerStyle.swigToEnum(AdaptiveCardObjectModelJNI.TableRow_GetStyle(swigCPtr, this));
  }

  public void SetStyle(ContainerStyle value) {
    AdaptiveCardObjectModelJNI.TableRow_SetStyle(swigCPtr, this, value.swigValue());
  }

}
