/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class TableCell extends Container {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected TableCell(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.TableCell_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TableCell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_TableCell(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TableCell() {
    this(AdaptiveCardObjectModelJNI.new_TableCell__SWIG_0(), true);
  }

  public TableCell(TableCell arg0) {
    this(AdaptiveCardObjectModelJNI.new_TableCell__SWIG_1(TableCell.getCPtr(arg0), arg0), true);
  }

  public static TableCell DeserializeTableCellFromString(ParseContext context, String root) {
    long cPtr = AdaptiveCardObjectModelJNI.TableCell_DeserializeTableCellFromString(ParseContext.getCPtr(context), context, root);
    return (cPtr == 0) ? null : new TableCell(cPtr, true);
  }

  public static TableCell DeserializeTableCell(ParseContext context, JsonValue root) {
    long cPtr = AdaptiveCardObjectModelJNI.TableCell_DeserializeTableCell(ParseContext.getCPtr(context), context, JsonValue.getCPtr(root), root);
    return (cPtr == 0) ? null : new TableCell(cPtr, true);
  }

}
