/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class TableColumnDefinition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected TableColumnDefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TableColumnDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_TableColumnDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TableColumnDefinition() {
    this(AdaptiveCardObjectModelJNI.new_TableColumnDefinition(), true);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.TableColumnDefinition_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.TableColumnDefinition_SerializeToJsonValue(swigCPtr, this), true);
  }

  public HorizontalAlignment GetHorizontalCellContentAlignment() {
    return HorizontalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetHorizontalCellContentAlignment(swigCPtr, this));
  }

  public void SetHorizontalCellContentAlignment(HorizontalAlignment value) {
    AdaptiveCardObjectModelJNI.TableColumnDefinition_SetHorizontalCellContentAlignment(swigCPtr, this, value.swigValue());
  }

  public VerticalAlignment GetVerticalCellContentAlignment() {
    return VerticalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetVerticalCellContentAlignment(swigCPtr, this));
  }

  public void SetVerticalCellContentAlignment(VerticalAlignment value) {
    AdaptiveCardObjectModelJNI.TableColumnDefinition_SetVerticalCellContentAlignment(swigCPtr, this, value.swigValue());
  }

  public SWIGTYPE_p_std__optionalT_unsigned_int_t GetWidth() {
    return new SWIGTYPE_p_std__optionalT_unsigned_int_t(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetWidth(swigCPtr, this), true);
  }

  public void SetWidth(SWIGTYPE_p_std__optionalT_unsigned_int_t value) {
    AdaptiveCardObjectModelJNI.TableColumnDefinition_SetWidth(swigCPtr, this, SWIGTYPE_p_std__optionalT_unsigned_int_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__optionalT_unsigned_int_t GetPixelWidth() {
    return new SWIGTYPE_p_std__optionalT_unsigned_int_t(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetPixelWidth(swigCPtr, this), true);
  }

  public void SetPixelWidth(SWIGTYPE_p_std__optionalT_unsigned_int_t value) {
    AdaptiveCardObjectModelJNI.TableColumnDefinition_SetPixelWidth(swigCPtr, this, SWIGTYPE_p_std__optionalT_unsigned_int_t.getCPtr(value));
  }

  public static TableColumnDefinition Deserialize(ParseContext context, JsonValue root) {
    long cPtr = AdaptiveCardObjectModelJNI.TableColumnDefinition_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(root), root);
    return (cPtr == 0) ? null : new TableColumnDefinition(cPtr, true);
  }

  public static TableColumnDefinition DeserializeFromString(ParseContext context, String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.TableColumnDefinition_DeserializeFromString(ParseContext.getCPtr(context), context, jsonString);
    return (cPtr == 0) ? null : new TableColumnDefinition(cPtr, true);
  }

}
