/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class TableColumnDefinition {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected TableColumnDefinition(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TableColumnDefinition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_TableColumnDefinition(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TableColumnDefinition() {
    this(AdaptiveCardObjectModelJNI.new_TableColumnDefinition(), true);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.TableColumnDefinition_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.TableColumnDefinition_SerializeToJsonValue(swigCPtr, this), true);
  }

  public @androidx.annotation.Nullable HorizontalAlignment GetHorizontalCellContentAlignment() {
    StdOptionalHorizontalAlignment optvalue = new StdOptionalHorizontalAlignment(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetHorizontalCellContentAlignment(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public void SetHorizontalCellContentAlignment(@androidx.annotation.Nullable HorizontalAlignment value) {
    StdOptionalHorizontalAlignment optvalue = (value == null) ? new StdOptionalHorizontalAlignment() : new StdOptionalHorizontalAlignment(value);
    {
      AdaptiveCardObjectModelJNI.TableColumnDefinition_SetHorizontalCellContentAlignment(swigCPtr, this, StdOptionalHorizontalAlignment.getCPtr(optvalue), optvalue);
    }
  }

  public @androidx.annotation.Nullable VerticalContentAlignment GetVerticalCellContentAlignment() {
    StdOptionalVerticalContentAlignment optvalue = new StdOptionalVerticalContentAlignment(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetVerticalCellContentAlignment(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public void SetVerticalCellContentAlignment(@androidx.annotation.Nullable VerticalContentAlignment value) {
    StdOptionalVerticalContentAlignment optvalue = (value == null) ? new StdOptionalVerticalContentAlignment() : new StdOptionalVerticalContentAlignment(value);
    {
      AdaptiveCardObjectModelJNI.TableColumnDefinition_SetVerticalCellContentAlignment(swigCPtr, this, StdOptionalVerticalContentAlignment.getCPtr(optvalue), optvalue);
    }
  }

  public @androidx.annotation.Nullable Long GetWidth() {
    StdOptionalLong optvalue = new StdOptionalLong(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetWidth(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public void SetWidth(@androidx.annotation.Nullable Long value) {
    StdOptionalLong optvalue = (value == null) ? new StdOptionalLong() : new StdOptionalLong(value);
    {
      AdaptiveCardObjectModelJNI.TableColumnDefinition_SetWidth(swigCPtr, this, StdOptionalLong.getCPtr(optvalue), optvalue);
    }
  }

  public @androidx.annotation.Nullable Long GetPixelWidth() {
    StdOptionalLong optvalue = new StdOptionalLong(AdaptiveCardObjectModelJNI.TableColumnDefinition_GetPixelWidth(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public void SetPixelWidth(@androidx.annotation.Nullable Long value) {
    StdOptionalLong optvalue = (value == null) ? new StdOptionalLong() : new StdOptionalLong(value);
    {
      AdaptiveCardObjectModelJNI.TableColumnDefinition_SetPixelWidth(swigCPtr, this, StdOptionalLong.getCPtr(optvalue), optvalue);
    }
  }

  public static TableColumnDefinition Deserialize(ParseContext context, JsonValue root) {
    long cPtr = AdaptiveCardObjectModelJNI.TableColumnDefinition_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(root), root);
    return (cPtr == 0) ? null : new TableColumnDefinition(cPtr, true);
  }

  public static TableColumnDefinition DeserializeFromString(ParseContext context, String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.TableColumnDefinition_DeserializeFromString(ParseContext.getCPtr(context), context, jsonString);
    return (cPtr == 0) ? null : new TableColumnDefinition(cPtr, true);
  }

}
