/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class TextStyleConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TextStyleConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextStyleConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_TextStyleConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setWeight(TextWeight value) {
    AdaptiveCardObjectModelJNI.TextStyleConfig_weight_set(swigCPtr, this, value.swigValue());
  }

  public TextWeight getWeight() {
    return TextWeight.swigToEnum(AdaptiveCardObjectModelJNI.TextStyleConfig_weight_get(swigCPtr, this));
  }

  public void setSize(TextSize value) {
    AdaptiveCardObjectModelJNI.TextStyleConfig_size_set(swigCPtr, this, value.swigValue());
  }

  public TextSize getSize() {
    return TextSize.swigToEnum(AdaptiveCardObjectModelJNI.TextStyleConfig_size_get(swigCPtr, this));
  }

  public void setIsSubtle(boolean value) {
    AdaptiveCardObjectModelJNI.TextStyleConfig_isSubtle_set(swigCPtr, this, value);
  }

  public boolean getIsSubtle() {
    return AdaptiveCardObjectModelJNI.TextStyleConfig_isSubtle_get(swigCPtr, this);
  }

  public void setColor(ForegroundColor value) {
    AdaptiveCardObjectModelJNI.TextStyleConfig_color_set(swigCPtr, this, value.swigValue());
  }

  public ForegroundColor getColor() {
    return ForegroundColor.swigToEnum(AdaptiveCardObjectModelJNI.TextStyleConfig_color_get(swigCPtr, this));
  }

  public void setFontType(FontType value) {
    AdaptiveCardObjectModelJNI.TextStyleConfig_fontType_set(swigCPtr, this, value.swigValue());
  }

  public FontType getFontType() {
    return FontType.swigToEnum(AdaptiveCardObjectModelJNI.TextStyleConfig_fontType_get(swigCPtr, this));
  }

  public static TextStyleConfig Deserialize(JsonValue json, TextStyleConfig defaultValue) {
    return new TextStyleConfig(AdaptiveCardObjectModelJNI.TextStyleConfig_Deserialize(JsonValue.getCPtr(json), json, TextStyleConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public TextStyleConfig() {
    this(AdaptiveCardObjectModelJNI.new_TextStyleConfig(), true);
  }

}
