#!/bin/sh
HUSKY_SH="$(dirname "$0")/_/husky.sh"
if [ -f $HUSKY_SH ]; then
    . $HUSKY_SH
    cd source/nodejs
    NODEJS_FILES_CHANGED=`git status . --short | wc -l`
    if [ $NODEJS_FILES_CHANGED != "0" ]; then
        npx lint-staged
    fi
fi

