require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'RNAdaptiveCards' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'RNAdaptiveCardsTests' do
    inherit! :complete
    # Pods for testing
  end

  # For enabling Flipper.
  # Note that if you use_framework!, flipper will not work.
  # Disable these lines if you are doing use_framework!
  use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'RNAdaptiveCards-tvOS' do
  # Pods for RNAdaptiveCards-tvOS

  target 'RNAdaptiveCards-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
