import * as markedschema from "marked-schema";
var fs = require("fs");
import { forEach } from "p-iteration";

export async function generateAsync() {

	var schemaModel = await markedschema.buildModel({
		schema: "../../../schemas/adaptive-card.json",
		toc: "./schema-explorer-toc.yml",
		rootDefinition: "AdaptiveCard",
		examplesPath: "../../../samples/v1.*"
	});
	
	var pages = [];

	await forEach(schemaModel, async (root: any) => {
		await forEach(root.children, async (child: any) => {

			var markdown = markedschema.generateMarkdown.createPropertiesSummary(child.properties, null, true, true, child.version);

			markdown = "# " + child.name + "\n\n" + markdown;

			var endAutoGeneratedTag = "<!-- END AUTO-GENERATED -->";
			markdown = "<!-- AUTO-GENERATED: This section is auto-generated from schemas/adaptive-card.json. Do NOT add anything above this or edit anything inside, it MUST be the first thing in the document and will be overwritten. -->\n\n" + markdown + endAutoGeneratedTag;

			var fileName = "../../../specs/elements/" + child.name + ".md";
			var finalFileContents;

			try {

				var data = await readFileAsync(fileName, "utf8");

				var endAutoGeneratedIndex = data.indexOf(endAutoGeneratedTag);
				if (endAutoGeneratedIndex === -1) {
					finalFileContents = markdown + "\n\n" + data;
				} else {
					endAutoGeneratedIndex += endAutoGeneratedTag.length;
					finalFileContents = markdown + data.substring(endAutoGeneratedIndex);
				}

			} catch (err) {

				// No existing file, add on the ## Rendering header
				finalFileContents = markdown + "\n\n## Rendering";

			}

			await writeFileAsync(fileName, finalFileContents);
		});
	});
}

function readFileAsync(fileName: string, encoding: string) : Promise<string> {
	return new Promise(function(resolve, reject) {
		fs.readFile(fileName, encoding, (err, data) => {
			if (err) {
				reject(err);
			} else {
				resolve(data);
			}
		});
	});
}

function writeFileAsync(fileName: string, contents: string) : Promise<void> {
	return new Promise(function(resolve, reject) {
		fs.writeFile(fileName, contents, (err) => {
			if (err) {
				reject(err);
			} else {
				resolve();
			}
		})
	});
}