/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class CardElementSize {
  public final static CardElementSize Auto = new CardElementSize("Auto", AdaptiveCardObjectModelJNI.CardElementSize_Auto_get());
  public final static CardElementSize Stretch = new CardElementSize("Stretch");
  public final static CardElementSize Small = new CardElementSize("Small");
  public final static CardElementSize Medium = new CardElementSize("Medium");
  public final static CardElementSize Large = new CardElementSize("Large");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CardElementSize swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CardElementSize.class + " with value " + swigValue);
  }

  private CardElementSize(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CardElementSize(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CardElementSize(String swigName, CardElementSize swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CardElementSize[] swigValues = { Auto, Stretch, Small, Medium, Large };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

