/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class CardElementType {
  public final static CardElementType AdaptiveCardType = new CardElementType("AdaptiveCardType", AdaptiveCardObjectModelJNI.CardElementType_AdaptiveCardType_get());
  public final static CardElementType TextBlockType = new CardElementType("TextBlockType");
  public final static CardElementType ImageType = new CardElementType("ImageType");
  public final static CardElementType FactGroupType = new CardElementType("FactGroupType");
  public final static CardElementType ColumnGroupType = new CardElementType("ColumnGroupType");
  public final static CardElementType ImageGalleryType = new CardElementType("ImageGalleryType");
  public final static CardElementType ActionGroupType = new CardElementType("ActionGroupType");
  public final static CardElementType ContainerType = new CardElementType("ContainerType");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static CardElementType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + CardElementType.class + " with value " + swigValue);
  }

  private CardElementType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private CardElementType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private CardElementType(String swigName, CardElementType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static CardElementType[] swigValues = { AdaptiveCardType, TextBlockType, ImageType, FactGroupType, ColumnGroupType, ImageGalleryType, ActionGroupType, ContainerType };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

