/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.adaptivecards.objectmodel;

public final class TextWrap {
  public final static TextWrap NoWrap = new TextWrap("NoWrap", AdaptiveCardObjectModelJNI.TextWrap_NoWrap_get());
  public final static TextWrap Wrap = new TextWrap("Wrap");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TextWrap swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TextWrap.class + " with value " + swigValue);
  }

  private TextWrap(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TextWrap(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TextWrap(String swigName, TextWrap swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TextWrap[] swigValues = { NoWrap, Wrap };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

