// DO NOT EDIT - Auto generated
// Generated with objc_convertor_enum.j2

#import "ACSAdaptiveCardSchemaKeyConvertor.h"
#import "../../../../../shared/cpp/ObjectModel/Enums.h"
// #import "ConversionUtils.h"
#import "SwiftInterfaceHeader.h"
#import "ACSAdaptiveCardSchemaKey.h"

@implementation ACSAdaptiveCardSchemaKeyConvertor


+(enum ACSAdaptiveCardSchemaKey) convertCpp:(AdaptiveCards::AdaptiveCardSchemaKey) adaptiveCardSchemaKeyCpp
{
  switch(adaptiveCardSchemaKeyCpp)
  {
    case AdaptiveCards::AdaptiveCardSchemaKey::Accent:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAccent;
    case AdaptiveCards::AdaptiveCardSchemaKey::ActionAlignment:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionAlignment;
    case AdaptiveCards::AdaptiveCardSchemaKey::ActionMode:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionMode;
    case AdaptiveCards::AdaptiveCardSchemaKey::ActionOrientation:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionOrientation;
    case AdaptiveCards::AdaptiveCardSchemaKey::ActionSet:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionSet;
    case AdaptiveCards::AdaptiveCardSchemaKey::ActionSetConfig:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionSetConfig;
    case AdaptiveCards::AdaptiveCardSchemaKey::Actions:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActions;
    case AdaptiveCards::AdaptiveCardSchemaKey::ActionsOrientation:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionsOrientation;
    case AdaptiveCards::AdaptiveCardSchemaKey::AdaptiveCard:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAdaptiveCard;
    case AdaptiveCards::AdaptiveCardSchemaKey::AllowCustomStyle:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAllowCustomStyle;
    case AdaptiveCards::AdaptiveCardSchemaKey::AllowInlinePlayback:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAllowInlinePlayback;
    case AdaptiveCards::AdaptiveCardSchemaKey::AltText:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAltText;
    case AdaptiveCards::AdaptiveCardSchemaKey::AssociatedInputs:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAssociatedInputs;
    case AdaptiveCards::AdaptiveCardSchemaKey::Attention:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAttention;
    case AdaptiveCards::AdaptiveCardSchemaKey::BackgroundColor:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBackgroundColor;
    case AdaptiveCards::AdaptiveCardSchemaKey::BackgroundImage:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBackgroundImage;
    case AdaptiveCards::AdaptiveCardSchemaKey::BackgroundImageUrl:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBackgroundImageUrl;
    case AdaptiveCards::AdaptiveCardSchemaKey::BaseCardElement:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBaseCardElement;
    case AdaptiveCards::AdaptiveCardSchemaKey::BaseContainerStyle:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBaseContainerStyle;
    case AdaptiveCards::AdaptiveCardSchemaKey::Bleed:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBleed;
    case AdaptiveCards::AdaptiveCardSchemaKey::Body:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBody;
    case AdaptiveCards::AdaptiveCardSchemaKey::Bolder:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBolder;
    case AdaptiveCards::AdaptiveCardSchemaKey::BorderColor:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBorderColor;
    case AdaptiveCards::AdaptiveCardSchemaKey::BorderThickness:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBorderThickness;
    case AdaptiveCards::AdaptiveCardSchemaKey::Bottom:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBottom;
    case AdaptiveCards::AdaptiveCardSchemaKey::ButtonSpacing:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyButtonSpacing;
    case AdaptiveCards::AdaptiveCardSchemaKey::Card:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyCard;
    case AdaptiveCards::AdaptiveCardSchemaKey::Center:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyCenter;
    case AdaptiveCards::AdaptiveCardSchemaKey::ChoiceSet:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyChoiceSet;
    case AdaptiveCards::AdaptiveCardSchemaKey::Choices:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyChoices;
    case AdaptiveCards::AdaptiveCardSchemaKey::Color:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColor;
    case AdaptiveCards::AdaptiveCardSchemaKey::ColorConfig:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColorConfig;
    case AdaptiveCards::AdaptiveCardSchemaKey::Column:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColumn;
    case AdaptiveCards::AdaptiveCardSchemaKey::ColumnSet:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColumnSet;
    case AdaptiveCards::AdaptiveCardSchemaKey::Columns:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColumns;
    case AdaptiveCards::AdaptiveCardSchemaKey::Container:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyContainer;
    case AdaptiveCards::AdaptiveCardSchemaKey::ContainerStyles:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyContainerStyles;
    case AdaptiveCards::AdaptiveCardSchemaKey::Dark:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDark;
    case AdaptiveCards::AdaptiveCardSchemaKey::Data:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyData;
    case AdaptiveCards::AdaptiveCardSchemaKey::DateInput:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDateInput;
    case AdaptiveCards::AdaptiveCardSchemaKey::Default:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDefault;
    case AdaptiveCards::AdaptiveCardSchemaKey::DefaultPoster:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDefaultPoster;
    case AdaptiveCards::AdaptiveCardSchemaKey::ElementId:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyElementId;
    case AdaptiveCards::AdaptiveCardSchemaKey::Emphasis:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyEmphasis;
    case AdaptiveCards::AdaptiveCardSchemaKey::ErrorMessage:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyErrorMessage;
    case AdaptiveCards::AdaptiveCardSchemaKey::ExtraLarge:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyExtraLarge;
    case AdaptiveCards::AdaptiveCardSchemaKey::FactSet:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFactSet;
    case AdaptiveCards::AdaptiveCardSchemaKey::Facts:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFacts;
    case AdaptiveCards::AdaptiveCardSchemaKey::Fallback:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFallback;
    case AdaptiveCards::AdaptiveCardSchemaKey::FallbackText:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFallbackText;
    case AdaptiveCards::AdaptiveCardSchemaKey::FillMode:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFillMode;
    case AdaptiveCards::AdaptiveCardSchemaKey::FontFamily:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontFamily;
    case AdaptiveCards::AdaptiveCardSchemaKey::FontSizes:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontSizes;
    case AdaptiveCards::AdaptiveCardSchemaKey::FontType:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontType;
    case AdaptiveCards::AdaptiveCardSchemaKey::FontTypes:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontTypes;
    case AdaptiveCards::AdaptiveCardSchemaKey::FontWeights:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontWeights;
    case AdaptiveCards::AdaptiveCardSchemaKey::ForegroundColor:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyForegroundColor;
    case AdaptiveCards::AdaptiveCardSchemaKey::ForegroundColors:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyForegroundColors;
    case AdaptiveCards::AdaptiveCardSchemaKey::Good:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyGood;
    case AdaptiveCards::AdaptiveCardSchemaKey::Height:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHeight;
    case AdaptiveCards::AdaptiveCardSchemaKey::Highlight:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHighlight;
    case AdaptiveCards::AdaptiveCardSchemaKey::HighlightColor:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHighlightColor;
    case AdaptiveCards::AdaptiveCardSchemaKey::HighlightColors:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHighlightColors;
    case AdaptiveCards::AdaptiveCardSchemaKey::HorizontalAlignment:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHorizontalAlignment;
    case AdaptiveCards::AdaptiveCardSchemaKey::IconPlacement:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIconPlacement;
    case AdaptiveCards::AdaptiveCardSchemaKey::IconSize:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIconSize;
    case AdaptiveCards::AdaptiveCardSchemaKey::IconUrl:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIconUrl;
    case AdaptiveCards::AdaptiveCardSchemaKey::Id:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyId;
    case AdaptiveCards::AdaptiveCardSchemaKey::Image:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImage;
    case AdaptiveCards::AdaptiveCardSchemaKey::ImageBaseUrl:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageBaseUrl;
    case AdaptiveCards::AdaptiveCardSchemaKey::ImageSet:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageSet;
    case AdaptiveCards::AdaptiveCardSchemaKey::ImageSize:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageSize;
    case AdaptiveCards::AdaptiveCardSchemaKey::ImageSizes:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageSizes;
    case AdaptiveCards::AdaptiveCardSchemaKey::Images:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImages;
    case AdaptiveCards::AdaptiveCardSchemaKey::InlineAction:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInlineAction;
    case AdaptiveCards::AdaptiveCardSchemaKey::Inlines:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInlines;
    case AdaptiveCards::AdaptiveCardSchemaKey::InlineTopMargin:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInlineTopMargin;
    case AdaptiveCards::AdaptiveCardSchemaKey::Inputs:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInputs;
    case AdaptiveCards::AdaptiveCardSchemaKey::InputSpacing:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInputSpacing;
    case AdaptiveCards::AdaptiveCardSchemaKey::IsMultiSelect:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsMultiSelect;
    case AdaptiveCards::AdaptiveCardSchemaKey::IsMultiline:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsMultiline;
    case AdaptiveCards::AdaptiveCardSchemaKey::IsRequired:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsRequired;
    case AdaptiveCards::AdaptiveCardSchemaKey::IsSelected:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsSelected;
    case AdaptiveCards::AdaptiveCardSchemaKey::IsSubtle:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsSubtle;
    case AdaptiveCards::AdaptiveCardSchemaKey::IsVisible:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsVisible;
    case AdaptiveCards::AdaptiveCardSchemaKey::Italic:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyItalic;
    case AdaptiveCards::AdaptiveCardSchemaKey::Items:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyItems;
    case AdaptiveCards::AdaptiveCardSchemaKey::Label:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLabel;
    case AdaptiveCards::AdaptiveCardSchemaKey::Language:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLanguage;
    case AdaptiveCards::AdaptiveCardSchemaKey::Large:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLarge;
    case AdaptiveCards::AdaptiveCardSchemaKey::Left:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLeft;
    case AdaptiveCards::AdaptiveCardSchemaKey::Light:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLight;
    case AdaptiveCards::AdaptiveCardSchemaKey::Lighter:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLighter;
    case AdaptiveCards::AdaptiveCardSchemaKey::LineColor:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLineColor;
    case AdaptiveCards::AdaptiveCardSchemaKey::LineThickness:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLineThickness;
    case AdaptiveCards::AdaptiveCardSchemaKey::Max:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMax;
    case AdaptiveCards::AdaptiveCardSchemaKey::MaxActions:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxActions;
    case AdaptiveCards::AdaptiveCardSchemaKey::MaxImageHeight:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxImageHeight;
    case AdaptiveCards::AdaptiveCardSchemaKey::MaxLength:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxLength;
    case AdaptiveCards::AdaptiveCardSchemaKey::MaxLines:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxLines;
    case AdaptiveCards::AdaptiveCardSchemaKey::MaxWidth:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxWidth;
    case AdaptiveCards::AdaptiveCardSchemaKey::Media:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMedia;
    case AdaptiveCards::AdaptiveCardSchemaKey::Medium:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMedium;
    case AdaptiveCards::AdaptiveCardSchemaKey::Method:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMethod;
    case AdaptiveCards::AdaptiveCardSchemaKey::MimeType:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMimeType;
    case AdaptiveCards::AdaptiveCardSchemaKey::Min:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMin;
    case AdaptiveCards::AdaptiveCardSchemaKey::MinHeight:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMinHeight;
    case AdaptiveCards::AdaptiveCardSchemaKey::Monospace:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMonospace;
    case AdaptiveCards::AdaptiveCardSchemaKey::NumberInput:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyNumberInput;
    case AdaptiveCards::AdaptiveCardSchemaKey::OptionalInputs:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyOptionalInputs;
    case AdaptiveCards::AdaptiveCardSchemaKey::Padding:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPadding;
    case AdaptiveCards::AdaptiveCardSchemaKey::Placeholder:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPlaceholder;
    case AdaptiveCards::AdaptiveCardSchemaKey::PlayButton:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPlayButton;
    case AdaptiveCards::AdaptiveCardSchemaKey::Poster:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPoster;
    case AdaptiveCards::AdaptiveCardSchemaKey::Regex:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRegex;
    case AdaptiveCards::AdaptiveCardSchemaKey::Repeat:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRepeat;
    case AdaptiveCards::AdaptiveCardSchemaKey::RepeatHorizontally:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRepeatHorizontally;
    case AdaptiveCards::AdaptiveCardSchemaKey::RepeatVertically:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRepeatVertically;
    case AdaptiveCards::AdaptiveCardSchemaKey::RequiredInputs:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRequiredInputs;
    case AdaptiveCards::AdaptiveCardSchemaKey::Requires:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRequires;
    case AdaptiveCards::AdaptiveCardSchemaKey::RichTextBlock:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRichTextBlock;
    case AdaptiveCards::AdaptiveCardSchemaKey::Right:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRight;
    case AdaptiveCards::AdaptiveCardSchemaKey::SelectAction:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySelectAction;
    case AdaptiveCards::AdaptiveCardSchemaKey::Separator:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySeparator;
    case AdaptiveCards::AdaptiveCardSchemaKey::ShowActionMode:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyShowActionMode;
    case AdaptiveCards::AdaptiveCardSchemaKey::ShowCard:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyShowCard;
    case AdaptiveCards::AdaptiveCardSchemaKey::ShowCardActionConfig:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyShowCardActionConfig;
    case AdaptiveCards::AdaptiveCardSchemaKey::Size:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySize;
    case AdaptiveCards::AdaptiveCardSchemaKey::Small:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySmall;
    case AdaptiveCards::AdaptiveCardSchemaKey::Sources:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySources;
    case AdaptiveCards::AdaptiveCardSchemaKey::Spacing:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySpacing;
    case AdaptiveCards::AdaptiveCardSchemaKey::SpacingDefinition:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySpacingDefinition;
    case AdaptiveCards::AdaptiveCardSchemaKey::Speak:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySpeak;
    case AdaptiveCards::AdaptiveCardSchemaKey::Stretch:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyStretch;
    case AdaptiveCards::AdaptiveCardSchemaKey::Strikethrough:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyStrikethrough;
    case AdaptiveCards::AdaptiveCardSchemaKey::Style:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyStyle;
    case AdaptiveCards::AdaptiveCardSchemaKey::Subtle:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySubtle;
    case AdaptiveCards::AdaptiveCardSchemaKey::Suffix:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySuffix;
    case AdaptiveCards::AdaptiveCardSchemaKey::SupportsInteractivity:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySupportsInteractivity;
    case AdaptiveCards::AdaptiveCardSchemaKey::TargetElements:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTargetElements;
    case AdaptiveCards::AdaptiveCardSchemaKey::Text:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyText;
    case AdaptiveCards::AdaptiveCardSchemaKey::TextBlock:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextBlock;
    case AdaptiveCards::AdaptiveCardSchemaKey::TextConfig:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextConfig;
    case AdaptiveCards::AdaptiveCardSchemaKey::TextInput:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextInput;
    case AdaptiveCards::AdaptiveCardSchemaKey::TextWeight:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextWeight;
    case AdaptiveCards::AdaptiveCardSchemaKey::Thickness:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyThickness;
    case AdaptiveCards::AdaptiveCardSchemaKey::TimeInput:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTimeInput;
    case AdaptiveCards::AdaptiveCardSchemaKey::Title:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTitle;
    case AdaptiveCards::AdaptiveCardSchemaKey::ToggleInput:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyToggleInput;
    case AdaptiveCards::AdaptiveCardSchemaKey::Top:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTop;
    case AdaptiveCards::AdaptiveCardSchemaKey::Type:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyType;
    case AdaptiveCards::AdaptiveCardSchemaKey::Underline:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyUnderline;
    case AdaptiveCards::AdaptiveCardSchemaKey::Url:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyUrl;
    case AdaptiveCards::AdaptiveCardSchemaKey::Value:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyValue;
    case AdaptiveCards::AdaptiveCardSchemaKey::ValueOff:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyValueOff;
    case AdaptiveCards::AdaptiveCardSchemaKey::ValueOn:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyValueOn;
    case AdaptiveCards::AdaptiveCardSchemaKey::Version:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyVersion;
    case AdaptiveCards::AdaptiveCardSchemaKey::VerticalAlignment:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyVerticalAlignment;
    case AdaptiveCards::AdaptiveCardSchemaKey::VerticalContentAlignment:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyVerticalContentAlignment;
    case AdaptiveCards::AdaptiveCardSchemaKey::Warning:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWarning;
    case AdaptiveCards::AdaptiveCardSchemaKey::Weight:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWeight;
    case AdaptiveCards::AdaptiveCardSchemaKey::Width:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWidth;
    case AdaptiveCards::AdaptiveCardSchemaKey::Wrap:
      return ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWrap;
  }
}


+(AdaptiveCards::AdaptiveCardSchemaKey) convertObj:(enum ACSAdaptiveCardSchemaKey) adaptiveCardSchemaKeyObjc
{
  switch(adaptiveCardSchemaKeyObjc)
  {
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAccent:
      return AdaptiveCards::AdaptiveCardSchemaKey::Accent;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionAlignment:
      return AdaptiveCards::AdaptiveCardSchemaKey::ActionAlignment;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionMode:
      return AdaptiveCards::AdaptiveCardSchemaKey::ActionMode;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionOrientation:
      return AdaptiveCards::AdaptiveCardSchemaKey::ActionOrientation;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionSet:
      return AdaptiveCards::AdaptiveCardSchemaKey::ActionSet;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionSetConfig:
      return AdaptiveCards::AdaptiveCardSchemaKey::ActionSetConfig;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActions:
      return AdaptiveCards::AdaptiveCardSchemaKey::Actions;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyActionsOrientation:
      return AdaptiveCards::AdaptiveCardSchemaKey::ActionsOrientation;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAdaptiveCard:
      return AdaptiveCards::AdaptiveCardSchemaKey::AdaptiveCard;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAllowCustomStyle:
      return AdaptiveCards::AdaptiveCardSchemaKey::AllowCustomStyle;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAllowInlinePlayback:
      return AdaptiveCards::AdaptiveCardSchemaKey::AllowInlinePlayback;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAltText:
      return AdaptiveCards::AdaptiveCardSchemaKey::AltText;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAssociatedInputs:
      return AdaptiveCards::AdaptiveCardSchemaKey::AssociatedInputs;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyAttention:
      return AdaptiveCards::AdaptiveCardSchemaKey::Attention;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBackgroundColor:
      return AdaptiveCards::AdaptiveCardSchemaKey::BackgroundColor;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBackgroundImage:
      return AdaptiveCards::AdaptiveCardSchemaKey::BackgroundImage;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBackgroundImageUrl:
      return AdaptiveCards::AdaptiveCardSchemaKey::BackgroundImageUrl;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBaseCardElement:
      return AdaptiveCards::AdaptiveCardSchemaKey::BaseCardElement;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBaseContainerStyle:
      return AdaptiveCards::AdaptiveCardSchemaKey::BaseContainerStyle;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBleed:
      return AdaptiveCards::AdaptiveCardSchemaKey::Bleed;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBody:
      return AdaptiveCards::AdaptiveCardSchemaKey::Body;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBolder:
      return AdaptiveCards::AdaptiveCardSchemaKey::Bolder;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBorderColor:
      return AdaptiveCards::AdaptiveCardSchemaKey::BorderColor;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBorderThickness:
      return AdaptiveCards::AdaptiveCardSchemaKey::BorderThickness;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyBottom:
      return AdaptiveCards::AdaptiveCardSchemaKey::Bottom;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyButtonSpacing:
      return AdaptiveCards::AdaptiveCardSchemaKey::ButtonSpacing;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyCard:
      return AdaptiveCards::AdaptiveCardSchemaKey::Card;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyCenter:
      return AdaptiveCards::AdaptiveCardSchemaKey::Center;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyChoiceSet:
      return AdaptiveCards::AdaptiveCardSchemaKey::ChoiceSet;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyChoices:
      return AdaptiveCards::AdaptiveCardSchemaKey::Choices;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColor:
      return AdaptiveCards::AdaptiveCardSchemaKey::Color;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColorConfig:
      return AdaptiveCards::AdaptiveCardSchemaKey::ColorConfig;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColumn:
      return AdaptiveCards::AdaptiveCardSchemaKey::Column;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColumnSet:
      return AdaptiveCards::AdaptiveCardSchemaKey::ColumnSet;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyColumns:
      return AdaptiveCards::AdaptiveCardSchemaKey::Columns;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyContainer:
      return AdaptiveCards::AdaptiveCardSchemaKey::Container;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyContainerStyles:
      return AdaptiveCards::AdaptiveCardSchemaKey::ContainerStyles;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDark:
      return AdaptiveCards::AdaptiveCardSchemaKey::Dark;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyData:
      return AdaptiveCards::AdaptiveCardSchemaKey::Data;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDateInput:
      return AdaptiveCards::AdaptiveCardSchemaKey::DateInput;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDefault:
      return AdaptiveCards::AdaptiveCardSchemaKey::Default;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyDefaultPoster:
      return AdaptiveCards::AdaptiveCardSchemaKey::DefaultPoster;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyElementId:
      return AdaptiveCards::AdaptiveCardSchemaKey::ElementId;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyEmphasis:
      return AdaptiveCards::AdaptiveCardSchemaKey::Emphasis;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyErrorMessage:
      return AdaptiveCards::AdaptiveCardSchemaKey::ErrorMessage;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyExtraLarge:
      return AdaptiveCards::AdaptiveCardSchemaKey::ExtraLarge;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFactSet:
      return AdaptiveCards::AdaptiveCardSchemaKey::FactSet;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFacts:
      return AdaptiveCards::AdaptiveCardSchemaKey::Facts;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFallback:
      return AdaptiveCards::AdaptiveCardSchemaKey::Fallback;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFallbackText:
      return AdaptiveCards::AdaptiveCardSchemaKey::FallbackText;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFillMode:
      return AdaptiveCards::AdaptiveCardSchemaKey::FillMode;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontFamily:
      return AdaptiveCards::AdaptiveCardSchemaKey::FontFamily;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontSizes:
      return AdaptiveCards::AdaptiveCardSchemaKey::FontSizes;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontType:
      return AdaptiveCards::AdaptiveCardSchemaKey::FontType;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontTypes:
      return AdaptiveCards::AdaptiveCardSchemaKey::FontTypes;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyFontWeights:
      return AdaptiveCards::AdaptiveCardSchemaKey::FontWeights;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyForegroundColor:
      return AdaptiveCards::AdaptiveCardSchemaKey::ForegroundColor;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyForegroundColors:
      return AdaptiveCards::AdaptiveCardSchemaKey::ForegroundColors;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyGood:
      return AdaptiveCards::AdaptiveCardSchemaKey::Good;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHeight:
      return AdaptiveCards::AdaptiveCardSchemaKey::Height;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHighlight:
      return AdaptiveCards::AdaptiveCardSchemaKey::Highlight;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHighlightColor:
      return AdaptiveCards::AdaptiveCardSchemaKey::HighlightColor;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHighlightColors:
      return AdaptiveCards::AdaptiveCardSchemaKey::HighlightColors;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyHorizontalAlignment:
      return AdaptiveCards::AdaptiveCardSchemaKey::HorizontalAlignment;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIconPlacement:
      return AdaptiveCards::AdaptiveCardSchemaKey::IconPlacement;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIconSize:
      return AdaptiveCards::AdaptiveCardSchemaKey::IconSize;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIconUrl:
      return AdaptiveCards::AdaptiveCardSchemaKey::IconUrl;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyId:
      return AdaptiveCards::AdaptiveCardSchemaKey::Id;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImage:
      return AdaptiveCards::AdaptiveCardSchemaKey::Image;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageBaseUrl:
      return AdaptiveCards::AdaptiveCardSchemaKey::ImageBaseUrl;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageSet:
      return AdaptiveCards::AdaptiveCardSchemaKey::ImageSet;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageSize:
      return AdaptiveCards::AdaptiveCardSchemaKey::ImageSize;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImageSizes:
      return AdaptiveCards::AdaptiveCardSchemaKey::ImageSizes;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyImages:
      return AdaptiveCards::AdaptiveCardSchemaKey::Images;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInlineAction:
      return AdaptiveCards::AdaptiveCardSchemaKey::InlineAction;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInlines:
      return AdaptiveCards::AdaptiveCardSchemaKey::Inlines;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInlineTopMargin:
      return AdaptiveCards::AdaptiveCardSchemaKey::InlineTopMargin;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInputs:
      return AdaptiveCards::AdaptiveCardSchemaKey::Inputs;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyInputSpacing:
      return AdaptiveCards::AdaptiveCardSchemaKey::InputSpacing;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsMultiSelect:
      return AdaptiveCards::AdaptiveCardSchemaKey::IsMultiSelect;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsMultiline:
      return AdaptiveCards::AdaptiveCardSchemaKey::IsMultiline;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsRequired:
      return AdaptiveCards::AdaptiveCardSchemaKey::IsRequired;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsSelected:
      return AdaptiveCards::AdaptiveCardSchemaKey::IsSelected;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsSubtle:
      return AdaptiveCards::AdaptiveCardSchemaKey::IsSubtle;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyIsVisible:
      return AdaptiveCards::AdaptiveCardSchemaKey::IsVisible;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyItalic:
      return AdaptiveCards::AdaptiveCardSchemaKey::Italic;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyItems:
      return AdaptiveCards::AdaptiveCardSchemaKey::Items;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLabel:
      return AdaptiveCards::AdaptiveCardSchemaKey::Label;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLanguage:
      return AdaptiveCards::AdaptiveCardSchemaKey::Language;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLarge:
      return AdaptiveCards::AdaptiveCardSchemaKey::Large;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLeft:
      return AdaptiveCards::AdaptiveCardSchemaKey::Left;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLight:
      return AdaptiveCards::AdaptiveCardSchemaKey::Light;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLighter:
      return AdaptiveCards::AdaptiveCardSchemaKey::Lighter;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLineColor:
      return AdaptiveCards::AdaptiveCardSchemaKey::LineColor;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyLineThickness:
      return AdaptiveCards::AdaptiveCardSchemaKey::LineThickness;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMax:
      return AdaptiveCards::AdaptiveCardSchemaKey::Max;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxActions:
      return AdaptiveCards::AdaptiveCardSchemaKey::MaxActions;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxImageHeight:
      return AdaptiveCards::AdaptiveCardSchemaKey::MaxImageHeight;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxLength:
      return AdaptiveCards::AdaptiveCardSchemaKey::MaxLength;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxLines:
      return AdaptiveCards::AdaptiveCardSchemaKey::MaxLines;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMaxWidth:
      return AdaptiveCards::AdaptiveCardSchemaKey::MaxWidth;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMedia:
      return AdaptiveCards::AdaptiveCardSchemaKey::Media;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMedium:
      return AdaptiveCards::AdaptiveCardSchemaKey::Medium;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMethod:
      return AdaptiveCards::AdaptiveCardSchemaKey::Method;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMimeType:
      return AdaptiveCards::AdaptiveCardSchemaKey::MimeType;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMin:
      return AdaptiveCards::AdaptiveCardSchemaKey::Min;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMinHeight:
      return AdaptiveCards::AdaptiveCardSchemaKey::MinHeight;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyMonospace:
      return AdaptiveCards::AdaptiveCardSchemaKey::Monospace;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyNumberInput:
      return AdaptiveCards::AdaptiveCardSchemaKey::NumberInput;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyOptionalInputs:
      return AdaptiveCards::AdaptiveCardSchemaKey::OptionalInputs;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPadding:
      return AdaptiveCards::AdaptiveCardSchemaKey::Padding;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPlaceholder:
      return AdaptiveCards::AdaptiveCardSchemaKey::Placeholder;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPlayButton:
      return AdaptiveCards::AdaptiveCardSchemaKey::PlayButton;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyPoster:
      return AdaptiveCards::AdaptiveCardSchemaKey::Poster;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRegex:
      return AdaptiveCards::AdaptiveCardSchemaKey::Regex;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRepeat:
      return AdaptiveCards::AdaptiveCardSchemaKey::Repeat;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRepeatHorizontally:
      return AdaptiveCards::AdaptiveCardSchemaKey::RepeatHorizontally;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRepeatVertically:
      return AdaptiveCards::AdaptiveCardSchemaKey::RepeatVertically;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRequiredInputs:
      return AdaptiveCards::AdaptiveCardSchemaKey::RequiredInputs;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRequires:
      return AdaptiveCards::AdaptiveCardSchemaKey::Requires;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRichTextBlock:
      return AdaptiveCards::AdaptiveCardSchemaKey::RichTextBlock;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyRight:
      return AdaptiveCards::AdaptiveCardSchemaKey::Right;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySelectAction:
      return AdaptiveCards::AdaptiveCardSchemaKey::SelectAction;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySeparator:
      return AdaptiveCards::AdaptiveCardSchemaKey::Separator;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyShowActionMode:
      return AdaptiveCards::AdaptiveCardSchemaKey::ShowActionMode;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyShowCard:
      return AdaptiveCards::AdaptiveCardSchemaKey::ShowCard;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyShowCardActionConfig:
      return AdaptiveCards::AdaptiveCardSchemaKey::ShowCardActionConfig;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySize:
      return AdaptiveCards::AdaptiveCardSchemaKey::Size;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySmall:
      return AdaptiveCards::AdaptiveCardSchemaKey::Small;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySources:
      return AdaptiveCards::AdaptiveCardSchemaKey::Sources;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySpacing:
      return AdaptiveCards::AdaptiveCardSchemaKey::Spacing;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySpacingDefinition:
      return AdaptiveCards::AdaptiveCardSchemaKey::SpacingDefinition;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySpeak:
      return AdaptiveCards::AdaptiveCardSchemaKey::Speak;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyStretch:
      return AdaptiveCards::AdaptiveCardSchemaKey::Stretch;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyStrikethrough:
      return AdaptiveCards::AdaptiveCardSchemaKey::Strikethrough;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyStyle:
      return AdaptiveCards::AdaptiveCardSchemaKey::Style;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySubtle:
      return AdaptiveCards::AdaptiveCardSchemaKey::Subtle;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySuffix:
      return AdaptiveCards::AdaptiveCardSchemaKey::Suffix;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeySupportsInteractivity:
      return AdaptiveCards::AdaptiveCardSchemaKey::SupportsInteractivity;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTargetElements:
      return AdaptiveCards::AdaptiveCardSchemaKey::TargetElements;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyText:
      return AdaptiveCards::AdaptiveCardSchemaKey::Text;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextBlock:
      return AdaptiveCards::AdaptiveCardSchemaKey::TextBlock;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextConfig:
      return AdaptiveCards::AdaptiveCardSchemaKey::TextConfig;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextInput:
      return AdaptiveCards::AdaptiveCardSchemaKey::TextInput;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTextWeight:
      return AdaptiveCards::AdaptiveCardSchemaKey::TextWeight;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyThickness:
      return AdaptiveCards::AdaptiveCardSchemaKey::Thickness;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTimeInput:
      return AdaptiveCards::AdaptiveCardSchemaKey::TimeInput;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTitle:
      return AdaptiveCards::AdaptiveCardSchemaKey::Title;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyToggleInput:
      return AdaptiveCards::AdaptiveCardSchemaKey::ToggleInput;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyTop:
      return AdaptiveCards::AdaptiveCardSchemaKey::Top;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyType:
      return AdaptiveCards::AdaptiveCardSchemaKey::Type;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyUnderline:
      return AdaptiveCards::AdaptiveCardSchemaKey::Underline;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyUrl:
      return AdaptiveCards::AdaptiveCardSchemaKey::Url;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyValue:
      return AdaptiveCards::AdaptiveCardSchemaKey::Value;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyValueOff:
      return AdaptiveCards::AdaptiveCardSchemaKey::ValueOff;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyValueOn:
      return AdaptiveCards::AdaptiveCardSchemaKey::ValueOn;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyVersion:
      return AdaptiveCards::AdaptiveCardSchemaKey::Version;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyVerticalAlignment:
      return AdaptiveCards::AdaptiveCardSchemaKey::VerticalAlignment;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyVerticalContentAlignment:
      return AdaptiveCards::AdaptiveCardSchemaKey::VerticalContentAlignment;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWarning:
      return AdaptiveCards::AdaptiveCardSchemaKey::Warning;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWeight:
      return AdaptiveCards::AdaptiveCardSchemaKey::Weight;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWidth:
      return AdaptiveCards::AdaptiveCardSchemaKey::Width;
    case ACSAdaptiveCardSchemaKey::ACSAdaptiveCardSchemaKeyWrap:
      return AdaptiveCards::AdaptiveCardSchemaKey::Wrap;
  }
}

@end
