name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

pool:
  name: Hosted Ubuntu 1604
  demands: java

parameters:
- name: prerelease_tag
  displayName: Prerelease Tag (leave empty for final releases)
  type: string
  default: ''

steps:
  # TODO: Remove when Android Gradle Plugin 4.1 is stable.
  # Starting from AGP 4.1+, the required NDK version will be retrieved automatically, so this script will not be needed.
- bash: |
   #!/usr/bin/env bash
   
   unset ANDROID_NDK_HOME
   sudo ${ANDROID_HOME}/tools/bin/sdkmanager --verbose --install "ndk;21.0.6113669"
  displayName: 'Get NDK (TODO: Remove this step)'

- task: Gradle@2
  displayName: build
  inputs:
    gradleWrapperFile: source/android/gradlew
    workingDirectory: source/android
    tasks: 'adaptivecards:build'
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'publish'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publish'
    publishJUnitResults: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **/io/adaptivecards/**/*.aar
     **/io/adaptivecards/**/*.pom
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  env:
    prerelease_tag: ${{ parameters.prerelease_tag }}
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
