name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016
  demands: java

steps:

- task: Gradle@2
  displayName: build
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:build'
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'publish'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publishReleasePublicationToLocalDirectoryRepository'
    publishJUnitResults: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **/io/adaptivecards/**/*.aar
     **/io/adaptivecards/**/*.pom
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
  continueOnError: true
  condition: succeededOrFailed()

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSign Artifact'
  inputs:
    ConnectedServiceName: 'AdaptiveCards ESRP CodeSigning'
    FolderPath: $(build.artifactstagingdirectory)
    Pattern: *.aar,*.pom
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
       {
         "KeyCode":"CP-450778-Pgp",
         "OperationCode":"LinuxSign",
         "Parameters":{},
         "ToolName":"sign",
         "ToolVersion":"1.0"
       }
     ]

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
