name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

schedules:
- cron: "0 10 * * Mon-Fri"
  displayName: 3:00 AM Pacific (UTC-8) Daily Build (M-F)
  branches:
   include:
   - main

pool:
  vmImage: vs2017-win2016
  demands: java

parameters:
- name: prerelease_tag
  displayName: Prerelease Tag (leave empty for final releases)
  type: string
  default: 'nightly'

variables:
  # Capture build parameter to use as environment variable
  prerelease_tag: ${{ parameters.prerelease_tag }}

steps:
# Automated publish to Sonatype is not yet configured, so skip Nexus credentials
# - task: DownloadSecureFile@1
#   name: gradleproperties
#   displayName: 'Download secure file'
#   inputs:
#     secureFile: gradle.properties.4
# - bash: |
#    cp -f $(gradleproperties.secureFilePath)  ./source/android/adaptivecards/gradle.properties
#   displayName: 'Bash Script'

  # TODO: Remove when Android Gradle Plugin 4.1 is stable.
  # Starting from AGP 4.1+, the required NDK version will be retrieved automatically, so this script will not be needed.
- bash: |
   #!/usr/bin/env bash
   
   unset ANDROID_NDK_HOME
   sudo ${ANDROID_HOME}/tools/bin/sdkmanager --verbose --install "ndk;21.0.6113669"
  displayName: 'Get NDK (TODO: Remove this step)'

- task: Gradle@2
  displayName: 'gradlew adaptivecards:build'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:build'

- task: Gradle@2
  displayName: 'gradlew publish'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publish'
    publishJUnitResults: false
