name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

pool:
  name: Azure Pipelines
  vmImage: windows-2019
  demands: java

parameters:
- name: base_version
  displayName: Please enter the base version (i.e. MAJOR.MINOR.PATCH)
  type: string
- name: is_prerelease
  displayName: Is this a pre-release?
  type: boolean
  default: true
- name: prerelease_suffix
  displayName: "Please enter pre-release suffix (this is appended to the base version with a hyphen, only if pre-release checkbox selected above)"
  type: string
  default: beta.1

variables:
- group: AdaptiveCards-KVLink
- name: AC_FULL_VERSION_SPECIFIED
  value: true
- name: AC_VERSION_STRING
  ${{ if parameters.is_prerelease }}:
    value: ${{ format('{0}-{1}', parameters.base_version, parameters.prerelease_suffix) }}
  ${{ if not(parameters.is_prerelease) }}:
    value: ${{ parameters.base_version }}
- name: AC_APPEND_BUILD_NUMBER
  value: false

stages:
- stage: Staging
  jobs:
  - job: Staging
    steps:
    - task: Gradle@2
      displayName: build
      inputs:
        gradleWrapperFile: source/android/gradlew.bat
        workingDirectory: source/android
        tasks: 'adaptivecards:build'
        publishJUnitResults: false
        jdkVersionOption: 1.11

    - task: Gradle@2
      displayName: 'Gradle Unsigned Publication'
      inputs:
        gradleWrapperFile: source/android/gradlew.bat
        workingDirectory: source/android
        tasks: 'adaptivecards:publishUnsignedReleasePublicationToUnsignedArtifactRepository'
        publishJUnitResults: false
        jdkVersionOption: 1.11

    - task: Powershell@2
      name: prepareSigningTask
      displayName: 'Copy Files For Signing'
      inputs:
        targetType: inline
        script: |
         ls $(build.sourcesdirectory) -File -Recur | ?{
           $_.FullName -Match ".*\\io\\adaptivecards\\.*(.aar)$"
         } | %{
           $dest = (Join-Path $(build.artifactstagingdirectory) ($_.Name + ".asc"))
           echo "##vso[task.setvariable variable=aarSignaturePath;isOutput=true;]$dest"
           cp $_.FullName $dest
           echo "Copied aar to $dest for signing"
         }

         ls $(build.sourcesdirectory) -File -Recur | ?{
           $_.FullName -Match ".*\\io\\adaptivecards\\.*(.pom)$"
         } | %{
           $dest = (Join-Path $(build.artifactstagingdirectory) ($_.Name + ".asc"))
           echo "##vso[task.setvariable variable=pomSignaturePath;isOutput=true;]$dest"
           cp $_.FullName $dest
           echo "Copied pom to $dest for signing"
         }

    - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
      displayName: 'ESRP CodeSign (Detached PGP)'
      inputs:
        ConnectedServiceName: 'AdaptiveCards ESRP CodeSigning 2022'
        FolderPath: $(build.artifactstagingdirectory)
        Pattern: '*.asc'
        signConfigType: inlineSignParams
        inlineOperation: |
         [
           {
             "KeyCode":"CP-464385-Pgp",
             "OperationCode":"LinuxSign",
             "Parameters":{},
             "ToolName":"sign",
             "ToolVersion":"1.0"
           }
         ]

    - task: Gradle@2
      displayName: 'Gradle Signed Publish to Local Directory'
      inputs:
        gradleWrapperFile: source/android/gradlew.bat
        workingDirectory: source/android
        tasks: 'adaptivecards:publishSignedReleasePublicationToSignedArtifactRepository'
        publishJUnitResults: false
        jdkVersionOption: 1.11
      env:
        AC_AAR_SIGNATURE_PATH: $(prepareSigningTask.aarSignaturePath)
        AC_POM_SIGNATURE_PATH: $(prepareSigningTask.pomSignaturePath)

    - task: Powershell@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        targetType: inline
        script: |
         ls $(build.sourcesdirectory) -File -Recur | ?{
           $_.FullName -Match ".*\\signedArtifact\\.*(.aar|.pom|.aar.asc|.pom.asc)$"
         } | %{
           echo "Copying artifact $_.Name"
           cp $_.FullName (Join-Path $(build.artifactstagingdirectory) $_.Name)
         }

    - task: Gradle@2
      displayName: 'Gradle Signed Publish to OSSRH Staging'
      inputs:
        gradleWrapperFile: source/android/gradlew.bat
        workingDirectory: source/android
        tasks: 'adaptivecards:publishSignedReleasePublicationToSonatypeStagingRepository'
        publishJUnitResults: false
        jdkVersionOption: 1.11
      env:
        AC_SONATYPE_CREDENTIAL: $(SonatypeNexusOSSRH)
        AC_AAR_SIGNATURE_PATH: $(prepareSigningTask.aarSignaturePath)
        AC_POM_SIGNATURE_PATH: $(prepareSigningTask.pomSignaturePath)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- stage: NexusValidation
  jobs:
  - job: NexusValidation
    steps:
    - task: Gradle@2
      displayName: 'Validate Staging Artifact'
      inputs:
        gradleWrapperFile: source/android/gradlew.bat
        workingDirectory: source/android
        tasks: 'adaptivecards:closeRepository'
        publishJUnitResults: false
        jdkVersionOption: 1.11
      env:
        AC_SONATYPE_CREDENTIAL: $(SonatypeNexusOSSRH)
        
- stage: PublishToMavenCentral
  jobs:
  - job: ManualApproval
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please verify artifact integrity at http://oss.sonatype.org/'
  
  - job: ReleaseValidatedArtifact
    dependsOn: ManualApproval
    steps:
    - checkout: self
      persistCredentials: true

    - task: Gradle@2
      displayName: 'Release Validated Artifact to Maven Central'
      inputs:
        gradleWrapperFile: source/android/gradlew.bat
        workingDirectory: source/android
        tasks: 'adaptivecards:releaseRepository'
        publishJUnitResults: false
        jdkVersionOption: 1.11
      env:
        AC_SONATYPE_CREDENTIAL: $(SonatypeNexusOSSRH)

    - bash: |
       git config --global user.email "adaptivecardscore@microsoft.com"
       git config --global user.name "adaptivecards"
       git tag -a "android/adaptivecards-android@$AC_VERSION_STRING" -m "Released adaptivecards-android v$AC_VERSION_STRING"
       git checkout main
       sed --in-place 's/acVersion=.*/acVersion=${{ parameters.base_version }}/' gradle.properties
       git checkout -b "adaptivecards/post-release-$AC_VERSION_STRING"
       git add gradle.properties
       git commit -m "[Android] Bump to v${{ parameters.base_version }}"
       git push --tags --set-upstream origin "adaptivecards/post-release-$AC_VERSION_STRING"
       curl -i -u $AC_GHUSER:$AC_GHPAT -d '{ "title": "[Android] Bump to v${{ parameters.base_version }}", "head": "adaptivecards/post-release-$AC_VERSION_STRING", "base": "main", "body": "Auto-generated post-release pull request" }' https://api.github.com/repos/microsoft/adaptivecards/pulls

      workingDirectory: source/android/adaptivecards
      displayName: 'Update version file'
      env:
        AC_GHUSER: $(ghuser)
        AC_GHPAT: $(ghpat)

