name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

schedules:
- cron: "0 10 * * Mon-Fri"
  displayName: 3:00 AM Pacific (UTC-8) Daily Build (M-F)
  branches:
   include:
   - main

pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016
  demands: java

parameters:
- name: prerelease_tag
  displayName: Prerelease tag after version (x.y.z-tag)
  type: string
  default: 'nightly'
- name: append_build_number
  displayName: Append unique build number after tag? (x.y.z-tag.yy.mm.dd.n)
  type: boolean
  default: true

variables:
  # Capture build parameters to environment variables, which are used in build.gradle
  AC_IS_PRERELEASE: true
  AC_PRERELEASE_TAG: ${{ parameters.prerelease_tag }}
  AC_APPEND_BUILD_NUMBER: ${{ parameters.append_build_number }}

steps:
- task: Gradle@2
  displayName: 'gradlew adaptivecards:build'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:build'

- task: Gradle@2
  displayName: 'Gradle Unsigned Publish Local'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publishUnsignedReleasePublicationToUnsignedArtifactRepository'
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'Gradle Unsigned Publish to ADO'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publishUnsignedReleasePublicationToAzuredevopsRepository'
    publishJUnitResults: false

- task: Powershell@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    targetType: inline
    script: |
     ls $(build.sourcesdirectory) -File -Recur | ?{
       $_.FullName -Match ".*\\io\\adaptivecards\\.*(.aar|.pom)$"
     } | %{
       cp $_.FullName (Join-Path $(build.artifactstagingdirectory) $_.Name)
       
       # Additional copy to be converted into detached PGP signature by ESRP task
       cp $_.FullName (Join-Path $(build.artifactstagingdirectory) ($_.Name + ".asc"))
     }

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSign Artifact'
  inputs:
    ConnectedServiceName: 'AdaptiveCards ESRP CodeSigning'
    FolderPath: $(build.artifactstagingdirectory)
    Pattern: '*.asc'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
       {
         "KeyCode":"CP-464385-Pgp",
         "OperationCode":"LinuxSign",
         "Parameters":{},
         "ToolName":"sign",
         "ToolVersion":"1.0"
       }
     ]

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

