name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr:
  branches:
    include:
    - main
    - feature/*
    - release/*

trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
  batch: True

pool:
  name: Azure Pipelines
  vmImage: macOS-latest

jobs:
- job: Job1
  steps:
  - template: templates/android-test-template.yml
- job: Job2
  steps:
  - template: templates/android-test-template.yml
- job: Job3
  steps:
  - template: templates/android-test-template.yml