name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

pool:
  name: Hosted Ubuntu 1604
  demands: java

steps:

- task: Gradle@2
  displayName: build
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    tasks: 'adaptivecards:build'
    workingDirectory: source/android
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'publish'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    tasks: 'adaptivecards:publish'
    workingDirectory: source/android
    publishJUnitResults: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: |
     **/artifact/**
     
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
