name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr: none
trigger: none

pool:
  name: Azure Pipelines
  vmImage: vs2017-win2016
  demands: java

variables:
- group: AdaptiveCards-KVLink

steps:

- task: Gradle@2
  displayName: build
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:build'
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'Gradle Unsigned Publication'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publishUnsignedReleasePublicationToUnsignedArtifactRepository'
    publishJUnitResults: false

- task: Powershell@2
  displayName: 'Copy Files For Signing'
  inputs:
    targetType: inline
    script: |
     ls $(build.sourcesdirectory) -File -Recur | ?{
       $_.FullName -Match ".*\\io\\adaptivecards\\.*(.aar)$"
     } | %{
       $dest = (Join-Path $(build.artifactstagingdirectory) ($_.Name + ".asc"))
       [System.Environment]::SetEnvironmentVariable('AC_AAR_SIGNATURE_PATH', $dest, 'User')
       cp $_.FullName $dest
       echo "Copied aar to $dest for signing"
     }

     ls $(build.sourcesdirectory) -File -Recur | ?{
       $_.FullName -Match ".*\\io\\adaptivecards\\.*(.pom)$"
     } | %{
       $dest = (Join-Path $(build.artifactstagingdirectory) ($_.Name + ".asc"))
       [System.Environment]::SetEnvironmentVariable('AC_POM_SIGNATURE_PATH', $dest, 'User')
       cp $_.FullName $dest
       echo "Copied pom to $dest for signing"
     }

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSign (Detached PGP)'
  inputs:
    ConnectedServiceName: 'AdaptiveCards ESRP CodeSigning'
    FolderPath: $(build.artifactstagingdirectory)
    Pattern: '*.asc'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
       {
         "KeyCode":"CP-464385-Pgp",
         "OperationCode":"LinuxSign",
         "Parameters":{},
         "ToolName":"sign",
         "ToolVersion":"1.0"
       }
     ]


- task: Gradle@2
  displayName: 'Gradle Signed Publication'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publishSignedReleasePublicationToSignedArtifactRepository'
    publishJUnitResults: false

- task: Powershell@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    targetType: inline
    script: |
     ls $(build.sourcesdirectory) -File -Recur | ?{
       $_.FullName -Match ".*\\signedArtifact\\.*(.aar|.pom|.aar.asc|.pom.asc)$"
     } | %{
       cp $_.FullName (Join-Path $(build.artifactstagingdirectory) $_.Name)
     }

- task: Gradle@2
  displayName: 'Gradle Publish to OSSRH Staging'
  inputs:
    gradleWrapperFile: source/android/gradlew.bat
    workingDirectory: source/android
    tasks: 'adaptivecards:publishSignedReleasePublicationToSonatypeStagingRepository'
    publishJUnitResults: false
  env:
    AC_SONATYPE_CREDENTIAL: $(SonatypeNexusOSSRH)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

