name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr:
  branches:
    include:
    - main
    - feature/*
    - release/*

trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
  batch: True

variables:
  solution: source/uwp/AdaptiveCards.sln
  buildConfiguration: Release
  buildPlatform: x64

pool:
  name: Azure Pipelines
  vmImage: windows-2019

steps:
- template: templates/uwp-download-secure-files.yml

- task: NuGetToolInstaller@0
  name: NuGetToolInstaller1
  displayName: Use NuGet 5.x
  inputs:
    versionSpec: 5.x

- task: NuGetAuthenticate@1
  displayName: Authenticate to NuGet

- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    command: 'restore'
    feedsToUse: config
    nugetConfigPath: source/nuget.config
    restoreSolution: $(solution)
    verbosityRestore: Detailed

- task: VSBuild@1
  name: VSBuild3
  displayName: Build solution
  inputs:
    solution: $(solution)
    vsVersion: 16.0
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
    maximumCpuCount: true
    createLogFile: true
    logFileVerbosity: detailed

- task: VSTest@2
  displayName: 'VsTest - Unit Tests'
  inputs:
    testRunTitle: 'UWP Unit Tests'
    searchFolder: '$(System.DefaultWorkingDirectory)\source\uwp'
    testAssemblyVer2: |
     **\Release\UWPUnitTests.build.appxrecipe
     !**\obj\**
    otherConsoleOptions: '/Framework:FrameworkUap10'
    runInParallel: true
    runTestsInIsolation: true
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: True
    collectDumpOn: always

- task: VSTest@2
  displayName: 'VsTest - UI Tests'
  inputs:
    testRunTitle: 'UWP UI Tests'
    searchFolder: '$(System.DefaultWorkingDirectory)\source\uwp'
    testAssemblyVer2: |
     **\Release\netcoreapp2.1\UWPUITests.dll
     !**\obj\**
    uiTests: true
    runTestsInIsolation: true
    codeCoverageEnabled: true
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: True
    collectDumpOn: always

