name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr:
  branches:
    include:
    - main
    - feature/*
    - release/*

trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
  batch: True

variables:
  solution: source/uwp/winui3/AdaptiveCards.sln
  buildConfiguration: Release
  buildPlatform: x64

pool:
  name: Azure Pipelines
  vmImage: windows-latest

steps:
- task: NuGetToolInstaller@1
  name: NuGetToolInstaller1
  displayName: Use NuGet 6.4.x
  inputs:
    versionSpec: 6.4.x

- task: NuGetAuthenticate@1
  name: NuGetAuthenticate2

- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    command: 'restore'
    feedsToUse: config
    nugetConfigPath: source/nuget.config
    restoreSolution: $(solution)
    verbosityRestore: Detailed


- task: PowerShell@2
  displayName: 'Install Windows SDK'
  inputs:
    targetType: 'inline'
    script: |
      choco install windows-sdk-10-version-1809-all
      
      $winget = (Get-Command winget -ErrorAction SilentlyContinue)
      if (-not $winget) {
        Write-Host 'winget not found. Installing App Installer (DesktopAppInstaller) silently...'
        
        Invoke-WebRequest -Uri "https://aka.ms/getwinget" -OutFile "$env:Temp\AppInstaller.msixbundle"
        Add-AppxPackage -Path "$env:Temp\AppInstaller.msixbundle"
      }

      
      winget install --id Microsoft.WindowsSDK.10.0.22000 -e --silent --accept-package-agreements --accept-source-agreements

- task: VSBuild@1
  name: VSBuild4
  displayName: Build solution
  inputs:
    solution: $(solution)
    vsVersion: 16.0
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
    maximumCpuCount: true
    createLogFile: true
    logFileVerbosity: detailed

