name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr:
  branches:
    include:
    - main
    - feature/*
    - release/*

trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
  batch: True

variables:
  solution: source/uwp/winui3/AdaptiveCards.sln
  buildConfiguration: Release
  buildPlatform: x64

pool:
  name: Azure Pipelines
  vmImage: windows-2019

steps:
- task: NuGetToolInstaller@0
  name: NuGetToolInstaller1
  displayName: Use NuGet 6.x
  inputs:
    versionSpec: 6.x

- task: NuGetRestore@1
  name: NuGetCommand2
  displayName: NuGet restore
  inputs:
    solution: $(solution)
    selectOrConfig: config
    verbosity: '-'

- task: VSBuild@1
  name: VSBuild3
  displayName: Build solution
  inputs:
    solution: $(solution)
    vsVersion: 16.0
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
    maximumCpuCount: true
    createLogFile: true
    logFileVerbosity: detailed

