name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)

pr:
  branches:
    include:
    - main
    - feature/*
    - release/*

trigger:
  branches:
    include:
    - main
    - feature/*
    - release/*
  batch: True

variables:
  solution: source/uwp/winui3/AdaptiveCards.sln
  buildConfiguration: Release
  buildPlatform: x64

pool:
  name: Azure Pipelines
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: 'Install Windows SDK'
  inputs:
    targetType: 'inline'
    script: |
      choco install windows-sdk-10-version-1809-all

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 8.x'
  inputs:
    version: 8.x

- task: NuGetToolInstaller@0
  name: NuGetToolInstaller1
  displayName: Use NuGet 5.x
  inputs:
    versionSpec: 5.x

- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'
  inputs:
    nuGetServiceConnections: 'AdaptiveCards-Dependencies'

- task: NuGetCommand@2
  displayName: NuGet restore
  inputs:
    command: 'restore'
    feedsToUse: config
    nugetConfigPath: source/nuget.config
    restoreSolution: $(solution)
    verbosityRestore: Detailed

- task: VSBuild@1
  name: VSBuild4
  displayName: Build solution
  inputs:
    solution: $(solution)
    vsVersion: 17.0
    platform: $(buildPlatform)
    configuration: $(buildConfiguration)
    maximumCpuCount: true
    createLogFile: true
    logFileVerbosity: detailed

