name: accessibility-insights-daily

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * Mon-Fri' # 2AM PST (3AM PDT) Daily Scan (M-F)

jobs:
    accessibility-insights-daily:
        runs-on: ubuntu-latest
        steps:
            - name: Scan for accessibility issues
              uses: microsoft/accessibility-insights-action@v2
              with:
                  url: http://adaptivecards-ci.azurewebsites.net/samples
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  discovery-patterns: http://adaptivecards-ci.azurewebsites.net/samples[.*]

            - name: Upload report artifact
              uses: actions/upload-artifact@v2
              with:
                  name: accessibility-reports
                  path: ${{ github.workspace }}/_accessibility-reports
